export const HIRAGANA_RAW = `
あおい|AOI|AZUL
あかい|AKAI|ROJO
あかるい|AKARUI|LUMINOSO
あたたかい|ATATAKAI|TEMPLADO (EL CLIMA)
あたらしい|ATARASHII|NUEVO
あつい|ATSUI|GRUESO
あつい|ATSUI|CALUROSO (EL CLIMA)
あつい|ATSUI|CALIENTE (COSAS)
あぶない|ABUNAI|PELIGROSO
あまい|AMAI|DULCE
いい／よい|II/YOI|BUENO
いそがしい|ISOGASHII|OCUPADO
いたい|ITAI|DOLORIDO
いろいろ|IROIRO|VARIOS
うすい|USUI|LIGERO, LEVE, SUAVE
おいしい|OISHII|RICO, BUENO, SABROSO
おおきい|OOKII|GRANDE
おそい|OSOI|LENTO, TARDÍO
おなじ|ONAJI|IGUAL, MISMO
おもい|OMOI|PESADO
おもしろい|OMOSHIROI|INTERESANTE
からい|KARAI|PICANTE
かるい|KARUI|LIGERO
かわいい|KAWAII|BONITO
きいろい|KIIROI|AMARILLO
きたない|KITANAI|SUCIO
きらい|KIRAI|QUE NO GUSTA
きれい|KIREI|HERMOSO, BONITO
くらい|KURAI|OSCURO
くろい|KUROI|NEGRO
けっこう|KEKKOU|ASÍ ESTÁ BIEN
げんき|GENKI|SALUDABLE
さむい|SAMUI|FRÍO (CLIMA)
しずか|SHIZUKA|SILENCIOSO
じょうぶ|JOUBU|VIGOROSO, RESISTENTE
しろい|SHIROI|BLANCO
すずしい|SUZUSHII|FRESCO (CLIMA)
せまい|SEMAI|ESTRECHO
だいじょうぶ|DAIJOUBU|SIN PROBLEMAS
たいせつ|TAISETSU|IMPORTANTE, PRECIOSO
たかい|TAKAI|ALTO, CARO
たのしい|TANOSHII|DIVERTIDO, GRACIOSO
ちいさい|CHIISAI|PEQUEÑO
ちかい|CHIKAI|CERCANO
ちゃいろ|CHAIRO|COLOR CAFÉ
つぎ|TSUGI|SIGUIENTE, PRÓXIMO
つまらない|TSUMARANAI|ABURRIDO, INSIGNIFICANTE
つめたい|TSUMETAI|FRÍO (MATERIA)
つよい|TSUYOI|FUERTE
とおい|TOOI|LEJANO
となり|TONARI|VECINO, DE AL LADO
ながい|NAGAI|LARGO
にぎやか|NIGIYAKA|BULLICIOSO
はやい|HAYAI|TEMPRANO, PRONTO
はやい|HAYAI|RÁPIDO, VELOZ
ひくい|HIKUI|BAJO
ひま|HIMA|DESOCUPADO
ひろい|HIROI|ANCHO, AMPLIO
ふとい|FUTOI|GORDO
ふるい|FURUI|VIEJO
べんり|BENRI|ÚTIL, PRÁCTICO
ほそい|HOSOI|DELGADO
まずい|MAZUI|INSÍPIDO, MALO (DE SABOR)
まっすぐ|MASSUGU|DERECHO, RECTO, DIRECTO
まるい|MARUI|REDONDO, CIRCULAR
みじかい|MIJIKAI|CORTO
むずかしい|MUZUKASHII|DIFÍCIL
やさしい|YASASHII|FÁCIL
やすい|YASUI|BARATO
ゆうめい|YUUMEI|FAMOSO
りっぱ|RIPPA|ESPLÉNDIDO, ELEGANTE
わかい|WAKAI|JOVEN
わるい|WARUI|MALO
すき|SUKI|GUSTAR
だいすき|DAISUKI|ENCANTAR
ほしい|HOSHII|QUERER
ひつよう|HITSUYOU|NECESITAR
じょうず|JOUZU|HÁBIL, DIESTRO
へた|HETA|TORPE
いや|IYA|NO GUSTAR

BOSS_FRAS|わたしのくるまはあかいです|WATASHINOKURUMAHAAKAIDESU|Mi coche es rojo
BOSS_FRAS|このほんはおもしろいです|KONOHONHAOMOSHIROIIDESU|Este libro es interesante
BOSS_FRAS|あさごはんはとてもおいしいです|ASAGOHANHATOMOTOOISHIIDESU|El desayuno es muy rico
BOSS_FRAS|きょうのてんきはあたたかいです|KYOUNOTENKIHAATATAKAIDESU|El tiempo de hoy está templado
BOSS_FRAS|わたしのへやはひろいです|WATASHINOHEYAHAHIROIDESU|Mi habitación es amplia
BOSS_FRAS|このえいがはとてもたのしいです|KONOEIGAHATOMOTOTANOSHIIDESU|Esta película es muy divertida
BOSS_FRAS|にほんごはむずかしいです|NIHON GOHAMUZUKASHIIDESU|El japonés es difícil
BOSS_FRAS|あのやまはとてもたかいです|ANOYAMAHATOMOTOTAKAIDESU|Aquella montaña es muy alta
BOSS_FRAS|このかばんはやすいです|KONOKABANHAYASUIDESU|Este maletín es barato
BOSS_FRAS|わたしはすずしいひがすきです|WATASHIHASUZUSHIIHIGASUKIIDESU|Me gustan los días frescos
BOSS_FRAS|わたしはがくせいです|WATASHIWAGAKUSEIDESU|Yo soy estudiante.
BOSS_FRAS|おなまえはなんですか|ONAMAEWANANDESUKA|¿Cuál es tu nombre?
BOSS_FRAS|これはなんですか|KOREWANANDESUKA|¿Qué es esto?
BOSS_FRAS|どこへいきますか|DOKOEIKIMASUKA|¿A dónde vas?
BOSS_FRAS|おげんきですか|OGENKIDESUKA|¿Cómo estás?
BOSS_FRAS|あさごはんをたべます|ASAGOHANWOTABEMASU|Desayuno (como el desayuno).
BOSS_FRAS|にほんごがわかります|NIHONGOGAWAKARIMASU|Entiendo japonés.
BOSS_FRAS|たのしいですね|TANOSHIIDESUNE|Es divertido, ¿verdad?
BOSS_FRAS|いまなんじですか|IMANANJIDESUKA|¿Qué hora es ahora?
BOSS_FRAS|またあいましょう|MATAAIMASHOU|Vamos a vernos de nuevo.
`.trim(); // El .trim() quita líneas vacías automáticamente