export const KANJI_SEMANA_2_RAW = `

普通|ふつう|FUTSUU|ORDINARIO / COMÚN
普段(の)|ふだん(の)|FUDAN|HABITUAL / NORMALMENTE
回数券|かいすうけん|KAISUUKEN|ABONO DE VIAJES / TALONARIO DE BILLETES
乗車券|じょうしゃけん|JOUSHAKEN|BILLETE DE TRASPORTE / PASAJE
旅券|りょけん|RYOKEN|PASAPORTE
発券|ハッケン|HAKKEN|EMISIÓN DE UN BILLETE
数字|すうじ|SUUJI|NÚMERO / CÍFRA
数学|すうがく|SUUGAKU|MATEMÁTICAS
点数|てんすう|TENSUU|PUNTUACIÓN / NOTA
数を数える|かずをかぞえる|KAZUWOKAZOERU|CONTAR NÚMEROS
飛行機|ひこうき|HIKOUKI|AVIÓN
交通機関|こうつうきかん|KOUTSUUKIKAN|MEDIOS DE TRANSPORTE
自動券売機|じどうけんばいき|JIDOUKENBAIKI|MÁQUINA AUTOMÁTICA DE BILLETES
危機|きき|KIKI|CRISIS
復習|ふくしゅう|FUKUSHUU|REPASO
往復|おうふく|OUFUKU|VIAJE DE IDA Y VUELTA
回復|かいふく|KAIFUKU|RECUPERACIÓN / REHABILITACIÓN
破片|はへん|HAHEN|FRAGMENTO / ROPURA
片道切符|かたみちきっぷ|KATAMICHIKIPPU|BILLETE DE SOLO IDA
片付ける|かたづける|KATADUKERU|ORDENAR / RECOGER
片〜|かた〜|KATA|UN LADO / UNÁNIME
〜枚|〜まい|MAI|CONTADOR PARA OBJETOS PLANOS
枚数|まいすう|MAISUU|NÚMERO DE HOJAS O OBJETOS PLANOS
期間|きかん|KIKAN|PERÍODO DE TIEMPO
定期|ていき|TEIKI|PERÍODO FIJO / ABONO
定期券|ていきけん|TEIKIKEN|ABONO DE TRANSPORTE / PASE REGULAR
販売|はんばい|HANBAI|VENTA
自動販売機|じどうはんばいき|JIDOUHANBAIKI|MÁQUINA EXPENDEDORA
指定席|していせき|SHITEISEKI|ASIENTO RESERVADO
指|ゆび|YUBI|DEDO
指す|さす|SASU|APUNTAR / SEÑALAR
調整|ちょうせい|CHOUSEI|AJUSTE / REGULACIÓN
調子|ちょうし|CHOUSHI|CONDICIÓN / ESTADO / TONO
調べる|しらべる|SHIRABERU|INVESTIGAR / BUSCAR
整理券|せいりけん|SEIRIKEN|BILLETE NUMERADO DE TURNO
整備|せいび|SEIBI|MANTENIMIENTO / PUESTA A PUNTO
整う|ととのう|TOTONOU|ESTAR ORDENADO / ORGANIZADO
表|ひょう|HYOU|TABLA / LISTA / GRÁFICO
時刻表|じこくひょう|JIKOKUHYOU|HORARIO / CRONOGRAMA
発表|はっぴょう|HAPPYOU|ANUNCIO / PRESENTACIÓN
表|おもて|OMOTE|SUPERFICIE / FACHADA / CARA
表す|あらわす|ARAWASU|MOSTRAR / EXPRESAR
表示|ひょうじ|HYOUJI|INDICACIÓN / EXPOSICIÓN
指示|しじ|SHIJI|INSTRUCCIÓN / INDICACIÓN
掲示|けいじ|KEIJI|AVISO / CARTEL
示す|しめす|SHIMESU|MOSTRAR / SEÑALAR
現金|げんきん|GENKIN|DINERO EN EFECTIVO
表現|ひょうげん|HYOUGEN|EXPRESIÓN
現れる|あらわれる|ARAWARERU|APARECER / MANIFESTARSE
支店|してん|SHITEN|SUCURSAL
支持|しじ|SHIJI|APOYO / SOPORTE
支える|ささえる|SASAERU|SOSTENER / MANTENER
払う|はらう|HARAU|PAGAR / LIMPIAR
支払う|しはらう|SHIHARAU|EFECTUAR EL PAGO
支払機|しはらいき|SHIHARAIKI|MÁQUINA DE PAGO / CAJERO
預金|よきん|YOKIN|DEPÓSITO BANCARIO
預ける|あずける|AZUKERU|CONFIAR / DEPOSITAR / ENCOMENDAR
預かる|あずかる|AZUKARU|CUIDAR / QUEDARSE A CARGO DE
払い戻し|はらい戻し|HARAIMODOSHI|REEMBOLSO / DEVOLUCIÓN
戻る|もどる|MODORU|REGRESAR / VOLVER
残高照会|ざんだかしょうかい|ZANDAKASHOUKAI|CONSULTA DE SALDO
残る|のこる|NOKORU|QUEDAR / PERMANECER
残す|のこす|NOKOSU|DEJAR / DEJAR ATRÁS
照明|しょうめい|SHOUMEI|ILUMINACIÓN
対照的|たいしょうてき|TAISHOUTEKI|CONTRASTANTE
照らす|てらす|TERASU|ILUMINAR
硬貨|こうか|KOUKA|MONEDA
硬い|かたい|KATAI|DURO
貨物|かもつ|KAMOTSU|CARGA / MERCANCÍA / FLETE
通貨|つうか|TSUUKA|DIVISA / MONEDA DE CURSO LEGAL
確定|かくてい|KAKUTEI|DETERMINACIÓN / FIJACIÓN
明確(な)|めいかく(な)|MEIKAKU|CLARO / DEFINIDO
確か(な)|たしか(な)|TASHIKA|CIERTO / SEGURO
確かめる|たしかめる|TASHIKAMERU|CONFIRMAR / VERIFICAR
確認|かくにん|KAKUNIN|CONFIRMACIÓN
認める|みとめる|MITOMERU|ADMITIR / ACEPTAR / APROBAR
違法|いほう|IHOU|ILEGAL
違い|ちがい|CHIGAI|DIFERENCIA
間違える|まちがえる|MACHIGAERU|COMETER UN ERROR
間違い|まちがい|MACHIGAI|ERROR / EQUIVOCACIÓN
取材|しゅざい|SHUZAI|RECOPILACIÓN DE DATOS / REPORTAJE
取る|とる|TORU|TOMAR / COGER
取り消し|とりけし|TORIKESHI|CANCELACIÓN / ANULACIÓN
書き取り|かきとり|KAKITORI|DICTADO
聞き取り|ききとり|KIKITORI|COMPRENSIÓN AUDITIVA
消去|しょうきょ|SHOUKYO|ELIMINACIÓN / BORRADO
消える|きえる|KIERU|DESAPARECER / EXTINGUIRSE
消す|けす|KESU|APAGAR / BORRAR
消しゴム|けしゴム|KESHIGOMU|GOMA DE BORRAR
温度|おんど|ONDO|TEMPERATURA
体温計|たいおんけい|TAIONKEI|TERMÓMETRO
温室|おんしつ|ONSHITSU|INVERNADERO
温かい|あたたかい|ATATAKAI|CÁLIDO / TEMPLADO
冷静(な)|れいせい(な)|REISEI|CALMADO / SERENO
冷たい|つめたい|TSUMETAI|FRÍO (AL TACTO)
冷える|ひえる|HIERU|ENFRIARSE
冷やす|ひやす|HIYASU|ENFRIAR (ALGO)
冷める|さめる|SAMERU|ENFRIARSE (COMIDA / PASIÓN)
冷ます|さます|SAMASU|ENFRIAR ALGO (DEJAR ENFRIAR)
緑茶|りょくちゃ|RYOKUCHA|TÉ VERDE
新緑|しんりょく|SHINRYOKU|VERDOR FRESCO / NUEVA VEGETACIÓN
緑(色)|みどり(いろ)|MIDORI|COLOR VERDE
紅茶|こうちゃ|KOUCHA|TÉ NEGRO (TÉ ROJO)
口紅|くちべに|KUCHIBENI|LÁPIZ DE LABIOS
水玉|みずたま|MIZUTAMA|GOTA DE AGUA / LUNARES
玉|たま|TAMA|BOLA / ESFERA
十円玉|じゅうえんだま|JUUENDAMA|MONEDA DE DIEZ YENES
返事|へんじ|HENJI|RESPUESTA / CONTESTACIÓN
返却|へんきゃく|HENKYAKU|DEVOLUCIÓN (DE UN OBJETO)
返金|へんきん|HENKIN|REEMBOLSO / DEVOLUCIÓN DE DINERO
返す|かえす|KAESU|DEVOLVER (ALGO)
団体|だんたい|DANTAI|GRUPO / ORGANIZACIÓN
集団|しゅうだん|SHUUDAN|GRUPO / COLECTIVO
団地|だんち|DANCHI|COMPLEJO RESIDENCIAL / BARRIO DE EDIFICIOS
布団|ふとん|FUTON|FUTÓN (COLCHÓN JAPONÉS)
一般|いっぱん|IPPAN|GENERAL / COMÚN
全般|ぜんぱん|ZENPAN|EN GENERAL / LA TOTALIDAD
幼児|ようじ|YOUJI|BEBÉ / NIÑO PEQUEÑO
幼い|おさない|OSANAI|MUY JOVEN / INFANTIL
小児科|しょうにか|SHOUNIKA|PEDIATRÍA
児童|じどう|JIDOU|NIÑO / INFANTE
〜歳|〜さい|SAI|〜AÑOS DE EDAD
二十歳|はたち / にじゅっさい|HATACHI|20 AÑOS DE EDAD
未定|みてい|MITEI|INDEFINIDO / NO DECIDIDO
未来|みらい|MIRAI|FUTURO
未知|みち|MICHI|DESCONOCIDO
未〜|み〜|MI|AÚN NO / NO DETALLADO
未満|みまん|MIMAN|MENOS DE / INSUFICIENTE
満員|まんいん|MANIN|LLENO DE GENTE / COMPLETO
満足|まんぞく|MANZOKU|SATISFACCIÓN
満ちる|みちる|MICHIRU|ESTAR LLENO DE / COLMARSE
老人|ろうじん|ROUJIN|ANCIANO / PERSONA MAYOR
年老いた|としおいた|TOSHIOITA|ENVEJECIDO / DE EDAD AVANZADA
設定|せってい|SETTEI|CONFIGURACIÓN / AJUSTE
設計|せっけい|SEKKEI|DISEÑO / PLANIFICACIÓN
設備|せつび|SETSUBI|EQUIPAMIENTO / INSTALACIONES
換気|かんき|KANKI|VENTILACIÓN
運転切換|うんてんきりかえ|UNTENKIRIKAE|CAMBIO DE MODO DE OPERACIÓN
乗り換え|のりかえ|NORIKAE|TRANSBORDO / CAMBIO DE TREN
風向|ふうこう|FUUKOU|DIRECCIÓN DEL VIENTO
風の向き|かぜのむき|KAZENOMUKI|DIRECCIÓN DEL VIENTO
向かい|むかい|MUKAI|EL LADO OPUESTO / ENFRENTE
向こう|むこう|MUKOU|ALLÁ / AL OTRO LADO / MÁS ALLÁ
停止|ていし|TEISHI|PARADA / DETENCIÓN
停電|ていでん|TEIDEN|APAGÓN / CORTE DE LUZ
停車|ていしゃ|TEISHA|DETENCIÓN DE UN VEHÍCULO
暖房|だんぼう|DANBOU|CALEFACCIÓN
温暖(な)|おんだん(な)|ONDAN|TEMPLADO / CÁLIDO
暖かい|あたたかい|ATATAKAI|CÁLIDO / CALUROSO
除湿|じょしつ|JOSHITSU|DESHUMIDIFICACIÓN
掃除|そうじ|SOUJI|LIMPIEZA
除く|のぞく|NOZOKU|ELIMINAR / EXCLUIR
湿度|しつど|SHITSUDO|HUMEDAD
湿気|しっき|SHIKKI|HUMEDAD / VAPOR
湿る|しめる|SHIMERU|HUMEDECERSE
標準|ひょうじゅん|HYOUJUN|ESTÁNDAR / NORMA
目標|もくひょう|MOKUHYOU|OBJETIVO / META
標本|ひょうほん|HYOUHON|MUESTRA / ESPECÍMEN
倍|ばい|BAI|DOBLE / VECES
〜倍|〜ばい|BAI|〜VECES MÁS
〜巻|〜かん|KAN|CONTADOR PARA TOMOS O VOLÚMENES
巻く|まく|MAKU|ENROLLAR / ENVOLVER
巻き戻し|まき戻し|MAKIMODOSHI|REBOBINADO
録画|ろくが|ROKUGA|GRABACIÓN DE VÍDEO
録音|ろくおん|ROKUON|GRABACIÓN DE AUDIO
音量|おんりょう|ONRYOU|VOLUMEN DEL SONIDO
風量|ふうりょう|FUURYOU|FUERZA DEL VIENTO
分量|ぶんりょう|BUNRYOU|CANTIDAD / DOSIS
数量|すうりょう|SUURYOU|CANTIDAD / MONTO
量る|はかる|HAKARU|MEDIR / PESAR
予定|よてい|YOTEI|PLAN / AGENDA
予習|よしゅう|YOSHUU|PREPARACIÓN DE LA LECCIÓN
予備|よび|YOBI|RESERVA / REPUESTO
予算|よさん|YOSAN|PRESUPUESTO
予約|よやく|YOYAKU|RESERVA / CITA
約〜|やく〜|YAKU|APROXIMADAMENTE
約束|やくそく|YAKUSOKU|PROMESA / COMPROMISO
地帯|ちたい|CHITAI|ZONA / REGIÓN
携帯電話|けいたいでんわ|KEITAIDENWA|TELÉFONO MÓVIL
温帯|おんたい|ONTAI|ZONA TEMPLADA
帯|おび|OBI|OBI / CINTURÓN DEL KIMONO
保温|ほおん|HOON|RETENCIÓN DEL CALOR
保湿|ほしつ|HOSHITSU|RETENCIÓN DE LA HUMEDAD
保険|ほけん|HOKEN|SEGURO
保つ|たもつ|TAMOTSU|MANTENER / CONSERVAR
保留|ほりゅう|HORYUU|RESERVA / SUSPENSIÓN
留学|りゅうがく|RYUUGAKU|ESTUDIAR EN EL EXTRANJERO
停留所|ていりゅうじょ|TEIRYUUJO|PARADA DE AUTOBÚS
書留|かきとめ|KAKITOME|CORREO CERTIFICADO
保守的(な)|ほしゅてき(な)|HOSHUTEKI|CONSERVADOR
留守|るす|RUSU|AUSENCIA (DE CASA)
守る|まもる|MAMORU|PROTEGER / CUMPLIR
お守り|おまもり|OMAMORI|AMULETO DE LA SUERTE
伝言|でんごん|DENGON|MENSAJE
伝える|つたえる|TSUTAERU|TRANSMITIR / COMUNICAR
手伝う|てつだう|TETSUDAU|AYUDAR
返済|へんさい|HENSAI|REEMBOLSO / PAGO DE UNA DEUDA
済む|すむ|SUMU|TERMINAR / CONCLUIR
〜済み|〜ずみ|ZUMI|COMPLETADO / TERMINADO
用件|ようけん|YOUKEN|ASUNTO / NEGOCIO
件名|けんめい|KENMEI|ASUNTO / TEMA (DE UN CORREO)
事件|じけん|JIKEN|INCIDENTE / SUCESO
通信|つうしん|TSUUSHIN|CORRESPONDENCIA / COMUNICACIÓN
自信|じしん|JISHIN|CONFIANZA (EN UNO MISMO)
信じる|しんじる|SHINJIRU|CREER / CONFIAR
着信履歴|ちゃくしんりれき|CHAKUSHINRIREKI|HISTORIAL DE LLAMADAS RECIBIDAS
履歴書|りれきしょ|RIREKISHO|CURRÍCULUM VITAE
歴史|れきし|REKISHI|HISTORIA
受信箱|じゅしばこ|JUSHINBAKO|BANDEJA DE ENTRADA
送信箱|そうしんばこ|SOUSHINBAKO|BANDEJA DE SALIDA
ごみ箱|ごみばこ|GOMIBAKO|PAPELERA / PAPELERA DE RECICLAJE
新規|しんき|SHINKI|NUEVO / NUEVO PROYECTO
規定|きてい|KITEI|REGULACIÓN / NORMA
変換|へんかん|HENKAN|CONVERSIÓN
大変(な)|たいへん(な)|TAIHEN|MUY / SERIO / DIFÍCIL
変わる|かわる|KAWARU|CAMBIAR / TRANSFORMARSE
変える|かえる|KAERU|CAMBIAR (ALGO)
選択|せんたく|SENTAKU|SELECCIÓN / ELECCIÓN
選手|せんしゅ|SENSHU|ATLETA / JUGADOR
選考|せんこう|SENKOU|SELECCIÓN / EVALUACIÓN
選ぶ|えらぶ|ERABU|ELEGIR / ESCOGER
決定|けってい|KETTEI|DECISIÓN
決める|きめる|KIMERU|DECIDIR (ALGO)
決まる|きまる|KIMARU|QUEDAR DECIDIDO
登録|とうろく|TOUROKU|REGISTRO / INSCRIPCIÓN
登山|とざん|TOZAN|MONTAÑISMO / ALPINISMO
登場|とうじょう|TOUJOU|APARICIÓN / ENTRADA EN ESCENA
山登り|やまのぼり|YAMANOBORI|ESCALADA DE MONTAÑAS / ALPINISMO
編集|へんしゅう|HENSHUU|EDICIÓN / REDACCIÓN
長編|ちょうへん|CHOUHEN|OBRA LARGA / LARGOMETRAJE
短編|たんぺん|TANPEN|OBRA CORTA / CORTOMETRAJE
編み物|あみもの|AMIMONO|TEJIDO / LABORES DE PUNTO
機能|きのう|KINOU|FUNCIÓN
可能(な)|かのう(な)|KANOU|POSIBLE
能力|のうりょく|NOURYOKU|CAPACIDAD / HABILIDAD
修正|しゅうせい|SHUUSEI|ENMIENDA / MODIFICACIÓN / CORRECCIÓN
修理|しゅうり|SHUURI|REPARACIÓN / ARREGLO
修士|しゅうし|SHUUSHI|MAESTRÍA / POSTRADO / POSEEDOR DE UN MÁSTER
完了|かんりょう|KANRYOU|FINALIZACIÓN / TERMINACIÓN
完成|かんせい|KANSEI|COMPLETADO / LOGRO / PERFECCIONAMIENTO
完備|かんび|KANBI|ESTAR COMPLETAMENTE EQUIPADO
終了|しゅうりょう|SHUURYOU|FIN / EXPIRACIÓN / CONCLUSIÓN
修了|しゅうりょう|SHUURYOU|COMPLETACIÓN DE UN CURSO
画像|がぞう|GAZOU|IMAGEN / PINTURA / RETRATO
映像|えいぞう|EIZOU|REFLEJO / IMAGEN / VÍDEO
現像|げんぞう|GENZOU|REVELADO DE UNA FOTOGRAFÍA
書類|しょるい|SHORUI|DOCUMENTO
分類|ぶんるい|BUNRUI|CLASIFICACIÓN
人類|じんるい|JINRUI|LA RAZA HUMANA / HUMANIDAD
書式|しょしき|SHOSHIKI|FORMATO PRESCRITO / FORMULARIO
入学式|にゅうがくしき|NYUUGAKUSHIKI|CEREMONIA DE INGRESO ESCOLAR
日本式|にほんしき|NIHONSHIKI|ESTILO JAPONÉS
正式(な)|せいしき(な)|SEISHIKI|FORMAL / OFICIAL
中央|ちゅうおう|CHUUOU|CENTRO
保存|ほぞん|HOZON|PRESERVACIÓN / CONSERVACIÓN
生存|せいぞん|SEIZON|SUPERVIVENCIA
ご存知|ごぞんじ|GOZONJI|SABER / CONOCER (FORMA HUMILDE)
存在|そんざい|SONZAI|EXISTENCIA
認め印|みとめいん|MITOMEIN|SELLO PRIVADO / FIRMA DE RECONOCIMIENTO
印|しるし|SHIRUSHI|MARCA / SEÑAL / SÍMBOLO
目印|めじるし|MEJIRUSHI|SEÑAL / PUNTO DE REFERENCIA / MARCA VISUAL
印刷|いんさつ|INSATSU|IMPRESIÓN / IMPRIMIR
拡大|かくだい|KAKUDAI|AMPLIACIÓN / AGRANDAMIENTO
縮小|しゅくしょう|SHUKUSHOU|REDUCCIÓN / DISMINUCIÓN


// --- Frases del repertorio del Jefe (Se elegirán 2 al azar cada 1000 puntos) ---
//BOSS_FRAS|frase japonesa|Frase en Romaji|Traducción al español
BOSS_FRAS|勉強したところを、もう一度復習しましょう。|BENKYOUSHITATOKOROWOMOUICHIDOFUKUSHUUSHIMASHOU|“REPASEMOS UNA VEZ MÁS LO QUE HEMOS ESTUDIADO”.
BOSS_FRAS|手袋が片方しかない。どこで落としたのだろう。|TEBUKURAGAKATAHOUSHIKANAIDOKODEOTOSHITANODAROU|“SOLO TENGO UN GUANTE. ¿DÓNDE LO HABRÉ JAVADO CAER?”.
BOSS_FRAS|飛行機や電車などを交通機関という。|HIKOUKIYADENSHANADOWOKOUTSUUKIKANTOIU|“A LOS AVIONES, TRENES, ETC., SE LES LLAMA MEDIOS DE TRANSPORTE”.
BOSS_FRAS|私は通学に往復３時間かかります。|WATASHIHATSUUGAKUNIOUFUKUSANJIKANKAKARIMASU|“TARDO TRES HORAS EN VIAJE DE IDA Y VUELTA PARA IR A LA ESCUELA”.
BOSS_FRAS|ここでは係員の指示通りに駐車してください。|KOKODEHAKAKARIINNOSHIJIDOORINICHUUSHASHITEKUDASAI|“POR FAVOR, ESTACIONE AQUÍ SIGUIENDO LAS INSTRUCCIONES DEL PERSONAL”.
BOSS_FRAS|この時刻表に電車の発車時刻が書いてあります。|KONOJIKOKUHYOUNIDENSHANOHASSHAJIKOKUGAKAITEARIMASU|“LOS HORARIOS DE SALIDA DE LOS TRENES ESTÁN ESCRITOS EN ESTE HORARIO”.
BOSS_FRAS|銀行員「整理券をお取りになってお待ちください。」|GINKOUINSEIRIKENWOOTORININATTEOMACHIKUDASAI|“EMPLEADO BANCARIO: “POR FAVOR, TOME UN BILLETE DE TURNO Y ESPERE”.”
BOSS_FRAS|朝からおなかの調子がよくない。|ASAKARAONAKANOHOUSHIGAYOKUNAI|“NO ME SIENTO BIEN DEL ESTÓMAGO DESDE LA MAÑANA”.
BOSS_FRAS|この店は照明が明るくて気持ちがいい。|KONOMISEHASHOUMEIGAAKARUKUTEKIMOCHIGAII|“ESTA TIENDA TIENE UNA ILUMINACIÓN BRILLANTE Y ES AGRADABLE”.
BOSS_FRAS|私は家族や友人に支えられて生きています。|WATASHIHAKAZOKUYAYUIJINNISASAERARETEIKITEIMASU|“VIVO APOYADO POR MI FAMILIA Y AMIGOS”.
BOSS_FRAS|この日本語の表現は英語で何と言いますか。|KONONIHONGONOHYOUGENHAEIGODENANTOIIMASUKA|“¿CÓMO SE DICE ESTA EXPRESIÓN EN JAPONÉS EN INGLÉS?”.
BOSS_FRAS|銀行にお金を預ける。|GINKOUNIONEKANEWOAZUKERU|“DEPOSITAR DINERO EN EL BANCO”.
BOSS_FRAS|漢字の書き取りのテストで100点を取った。|KANJINOKAKITORINOTESTODEDYAKUTENWOTORTA|“SAQUÉ 100 PUNTOS EN EL EXAMEN DE DICTADO DE KANJI”.
BOSS_FRAS|「五百円硬貨はお使いになれません。」|GOHAKUENKOUKAHAOTSUTAINANAREMASEN|““NO SE PUEDEN UTILIZAR MONEDAS DE 500 YENES”.”
BOSS_FRAS|間違いを消しゴムで消して書き直す。|MACHIGAIWOKESHIGOMUDEKESHITEKAKINAOSU|“BORRAR EL ERROR CON UNA GOMA Y VOLVER A ESCRIBIRLO”.
BOSS_FRAS|電話番号をお確かめください。|DENWABANGOUWOOTASHIKAMEKUDASAI|“POR FAVOR, VERIFIQUE EL NÚMERO DE TELÉFONO”.
BOSS_FRAS|このデザートは冷やして食べるとおいしい。|KONODEZARTOHAHIYASHITETABERUTOOUISHII|“ESTE POSTRE ESTÁ DELICIOSO SI SE COME FRÍO”.
BOSS_FRAS|この辺は緑が多くて静かできれいですね。|KONOHENHAMIDORIGAOOKUTESHIZUKADEKIREIDESUNE|“ESTA ZONA TIENE MUCHO VERDOR, ES TRANQUILA Y HERMOSA, ¿VERDAD?”.
BOSS_FRAS|キャッシュバックというのは返金のことです。|KYASSHUBAKKUTOIUHOHAHENKINNOTODESU|“EL REEMBOLSO SIGNIFICA LA DEVOLUCIÓN DEL DINERO”.
BOSS_FRAS|この自動販売機は硬貨だけでなく千円札も使える。|KONOJIDOUHANBAIKIHAKOUKADAKEDE_NAKUSENENSATSUMOTSUKAERU|“ESTA MÁQUINA EXPENDEDORA NO SOLO ACEPTA MONEDAS sino TAMBIÉN BILLETES DE MIL YENES”.
BOSS_FRAS|「18歳未満」には18歳は入りません。|JUUHASSAIMIMANNIHAJUUHASSAIHAHAIRIMASEN|““MENOS DE 18 AÑOS” NO INCLUYE A LOS QUE TIENEN 18 AÑOS”.
BOSS_FRAS|小児科の医者の数が足りないそうです。|SHOUNIKANOISHANOKAZUGATARINAISOUDESU|“PARECE QUE EL NÚMERO DE PEDIATRAS ES INSUFICIENTE”.
BOSS_FRAS|団体旅行は安いが、自由に行動できない。|DANTAIRYOKOUHAYASUIGAJIYUUNI_KOUDOUDEKINAI|“LOS VIAJES EN GRUPO SON BARATOS, PERO NO SE PUEDE ACTUAR LIBREMENTE”.
BOSS_FRAS|冬の登山は危険に満ちている。|FUYUNOTOZANHAKIKENNIMITCHITERU|“EL MONTAÑISMO EN INVIERNO ESTÁ LLENO DE PELIGROS”.
BOSS_FRAS|梅雨の時期はエアコンを除湿にすると快適だ。|TSUYUNOJIKIHA_EAKONWOJOSHITSUNISURUTOKAITEKIDU|“DURANTE LA TEMPORADA DE LLUVIAS, ES CÓMODO PONER EL AIRE ACONDICIONADO EN MODO DESHUMIDIFICACIÓN”.
BOSS_FRAS|次の駅で地下鉄に乗り換えましょう。|TSUGINOEKIDETIKATETSUNINORIKAEMASHOU|“CAMBIEMOS AL SUBTERRÁNEO EN LA SIGUIENTE ESTACIÓN”.
BOSS_FRAS|室内の温度が高くなりすぎたら、設定温度を下げましょう。|SHITSUNAINOONDOGATAKUNARUSUGITARARASETTEIONDOWOSAGEMASHOU|“SI LA TEMPORADA INTERIOR SE ELEVA DEMASIADO, BAJEMOS LA TEMPERATURA CONFIGURADA”.
BOSS_FRAS|年中無休。ただし、年末年始を除く。|NENCHUUMUKYUUTADASHINENMATSUNENSHI_WONOZOKU|“ABIERTO TODO EL AÑO. SIN EMBARGO, SE EXCLUYEN LAS VACACIONES DE FIN DE AÑO Y AÑO NUEVO”.
BOSS_FRAS|テレビの音声切換をして英語で聞く。|TEREBINOONSEIKIRIKAEWOSHITEEIGODEKIKU|“CAMBIAR EL AUDIO DEL TELEVISOR PARA ESCUCHARLO EN INGLÉS”.
BOSS_FRAS|標準モードでビデオを予約録画する。|HYOUJUNMODODEBIDEOWOYOYAKUROKUGASURU|“PROGRAMAR LA GRABACIÓN DE UN VÍDEO EN MODO ESTÁNDAR”.
BOSS_FRAS|見終わったビデオは巻き戻ししてお返しください。|MIOWARTABIDEOHAMAKIMODOSHISHITEOKAESHIKUDASAI|“POR FAVOR, REBOBINE EL VÍDEO DESPUÉS DE VERLO Y DEVUÉLVALO”.
BOSS_FRAS|中国の人口は日本の約10倍です。|CHUUGOKUNOJINKOUHANIHONNOYAKUJUUBAIDESU|“LA POBLACIÓN DE CHINA ES APROXIMADAMENTE DIEZ VECES LA DE JAPÓN”.
BOSS_FRAS|この件は保留にしておいて、また後で考えます。|KONOKENHAHORYUUNISHITOITEMATAATODEKANGAEMASU|“DEJAREMOS ESTE ASUNTO EN SUSPENSO Y LO PENSAREMOS MÁS TARDE”.
BOSS_FRAS|大事な手紙やお金を郵便書留で送る。|DAIJINATEGAMIYAOKANEWOYUUBINKAKITOMEDEOKURU|“ENVIAR CARTAS IMPORTANTES O DINERO POR CORREO CERTIFICADO”.
BOSS_FRAS|家を買ったので毎月のローンの返済がたいへんだ。|IEWOKATTANODEMAITSUKINOROONNOHENSAIGATAIHENDAR|“COMO COMPRÉ UNA CASA, EL PAGO MENSUAL DE LA HIPOTECA ES DIFÍCIL”.
BOSS_FRAS|もうすぐ受験なので、神社でお守りを買った。|MOUSUGUJUKENNANODEJINJADEOOMAMORIWOKATTA|“COMO PRONTO SERÁ EL EXAMEN, COMPRÉ UN AMULETO EN EL SANTUARIO”.
BOSS_FRAS|車も人も、信号を守りましょう。|KURUMAMOHITOMOSHINGOUWOMAMORIMASHOU|“TANTO LOS COCHES COMO LAS PERSONAS, RESPETEMOS EL SEMÁFORO”.
BOSS_FRAS|携帯電話の電話番号が変わりましたので知らせます。|KEITAIDENWANODENWABANGOUGAKAWARIMASHITANODESHIRASEMASU|“LES INFORMO QUE MI NÚMERO DE TELÉFONO MÓVIL HA CAMBIADO”.
BOSS_FRAS|選考の結果、オリンピックに出場する選手が決まった。|SENKOUNOKEKKAORINPIKKUNISHUTSUJOUSURUSENSHUGAKIMATTA|“COMO RESULTADO DE LA SELECCIÓN, SE HAN DECIDIDO LOS ATLETAS QUE PARTICIPARÁN EN LOS JUEGOS OLÍMPICOS”.
BOSS_FRAS|メールを新規作成する。|MERUWOSHINKISAKUSEISURU|“CREAR UN NUEVO CORREO ELECTRÓNICO”.
BOSS_FRAS|このフィルムを現像してください。|KONOFIRUMUWOGENZOUSHITEKUDASAI|“POR FAVOR, REVELE ESTE CARRETE”.
BOSS_FRAS|コピー機の調子が悪いので修理に来てください。|KOPIIKINOTHOUSHIGAWARUINODESHUURINIKITEKUDASAI|“LA COPIADORA NO FUNCIONA BIEN, ASÍ QUE POR FAVOR VENGA A REPARARLA”.
BOSS_FRAS|この部屋はエアコン完備です。|KONOHEYAHAEAKONKANBIDESU|“ESTA HABITACIÓN ESTÁ COMPLETAMENTE EQUIPADA CON AIRE ACONDICIONADO”.
BOSS_FRAS|アドレスを登録する。|ADORESUWOTOUROKUSURU|“REGISTRAR UNA DIRECCIÓN”.
BOSS_FRAS|ここに受け取りの認め印をお願いします。|KOKONIUKETORINOMITOMEINWOONEGAISHIMASU|“POR FAVOR, PONGA AQUÍ SU SELLO DE RECONOCIMIENTO PARA LA ENTREGA”.
BOSS_FRAS|タイトルは中央に、日付と名前は右に書きます。|TAITORUHACHUUOUNIHIZUKETONAMAEHAMIGINIKAKIMASU|“EL TÍTULO SE ESCRIBE EN EL CENTRO, Y LA FECHA Y EL NOMBRE A LA DERECHA”.
BOSS_FRAS|ここにある書類を分類してファイルしてください。|KOKONIARUSHORUIWOBUNRUISHITEFAIRUSHITEKUDASAI|“POR FAVOR, CLASIFIQUE LOS DOCUMENTOS QUE ESTÁN AQUÍ Y ARCHÍVELOS”.
BOSS_FRAS|作成したファイルを保存する。|SAKUSEISHITAFAIRUWOHOZONSURU|“GUARDAR EL ARCHIVO CREADO”.

`.trim();