export const KANJI_SEMANA_6_RAW = `
得|とく|TOKU|BENEFICIO
得る|える|ERU|OBTENER
納得|なっとく|NATTOKU|DESCONOCIMIENTO
心得る|こころえる|KOKOROERU|NO　ENTENDER
広告|こうこく|KOUKOKU|ANUNCIO
警告|けいこく|KEIKOKU|PREOCUPACIÓN
報告|ほうこく|HOUKOKU|REPORTE
告げる|つげる|TSUGERU|INFORMAR
税金|ぜいきん|ZEIKIN|TASA
税関|ぜいかん|ZEIKAN|COSTE
消費税|しょうひぜい|SHOUHIZEI|COSTE DE CONSUMO
課税|かぜい|KAZEI|TASACCIÓN
定価|ていか|TEIKA|PRECIO ESTABLECIDO
物価|ぶっか|BUKKA|COSTE DE VIDA
価格|かかく|KAKAKU|PRECIO
性格|せいかく|SEIKAKU|PERSONALIDAD
超|ちょう|CHOU|SUPER
超える|こえる|KOERU|CRUZAR, PASAR POR
超過|ちょうか|CHOUKA|EXCESO
越す|こす|KOSU|CRUZAR, PASAR POR
平均|へいきん|HEIKIN|PROMEDIO
均一|きんいつ|KINITSU|UNIFORMIDAD
均等|きんとう|KINTOU|UNIFORME
靴|くつ|KUTSU|ZAPATOS
長靴|ながぐつ|NAGAGUTSU|BOTAS
靴下|くつした|KUTSUSHITA|CALCETINES
雨靴|あまぐつ|AMAGUTSU|BOTAS DE AGUA
子供|こども|KODOMO|NIÑO
提供|ていきょう|TEIKYOU|OFRECIMIENTO
印象|いんしょう|INSHOU|IMPRESIÓN
対象|たいしょう|TAISHOU|DESTINATARIO
現象|げんしょう|GENSHOU|FENÓMENO
象|ぞう|ZOU|ELEFANTE
組織|そしき|SOSHIKI|ORGANIZACIÓN
組み合わせ|くみあわせ|KUMIAWASE|COMBINACIÓN
番組|ばんぐみ|BANGUMI|PROGRAMA DE TV
組合|くみあい|KUMIAI|ASOCIACIÓN
価値|かち|KACHI|VALOR
値段|ねだん|NEDAN|PRECIO
数値|すうち|SUUCHI|VALOR NUMÉRICO
値|あたい|ATAI|VALOR
募集|ぼしゅう|BOSHUU|RECLUTAMIENTO
募金|ぼきん|BOKIN|RECAUDAR FONDOS
応募|おうぼ|OUBO|APLICACIÓN
募る|つのる|TSUNORU|COLECCIONAR
無料|むりょう|MURYOU|GRATIS
無事|ぶじ|MUJI|SEGURO
有無|うむ|UMU|EXISTENCIA Y NO EXISTENCIA
無し|なし|NASHI|NO
詰める|つめる|TSUMERU|RELLENAR / EMPAQUETAR / COMPRIMIR
缶詰|かんづめ|KANZUME|COMIDA ENLATADA / CONSERVA
箱詰め|はこづめ|HAKOZUME|EMPAQUETADO EN CAJA
小麦粉|こむぎこ|KOMUGIKO|HARINA (DE TRIGO)
麦畑|むぎばたけ|MUGIBATAKE|CAMPO DE TRIGO
純粋（な）|じゅんすい（な）|JUNSUI|PURO
純情（な）|じゅんじょう（な）|JUNJOU|DE CORAZÓN PURO / INOCENTE
単純（な）|たんじゅん（な）|TANJUN|SIMPLE / INGENUO
純米酢|じゅんまいす|JUNMAISU|VINAGRE DE ARROZ PURO
雑草|ざっそう|ZASSOU|MALA HIERBA
除草|じょそう|JOSOU|DESHIERBE / ESCARDA
草|くさ|KUSA|HIERBA / CÉSPED
草花|くさばな|KUSABANA|PLANTA CON FLORES
食塩|しょくえん|SHOKUEN|SAL DE MESA
塩|しお|SHIO|SAL
固定|こてい|KOTEI|ESTABILIDAD / FIJACIÓN
固体|こたい|KOTAI|SÓLIDO (CUERPO)
固形|こけい|KOKEI|SÓLIDO (FORMA)
固い|かたい|KATAI|DURO
固まる|かたまる|KATAMARU|ENDURECERSE
実演|じつえん|JITSUEN|DEMOSTRACIÓN / EXHIBICIÓN
演技|えんぎ|ENGI|ACTUACIÓN / INTERPRETACIÓN
演習|えんしゅう|ENSHUU|EJERCICIOS / MANIOBRAS
演説|えんぜつ|ENZETSU|DISCURSO / ORACIÓN
菓子|かし|KASHI|DULCES / GOLOSINAS
洋菓子|ようがし|YOUGASHI|DULCES OCCIDENTALES
和菓子|わがし|WAGASHI|DULCES JAPONESES
贈り物|おくりもの|OKURIMONO|REGALO / OBSEQUIO
贈る|おくる|OKURU|REGALAR / DAR UN PRESENTE
帰省|きせい|KISEI|REGRESO A CASA (NATAL)
反省|はんせい|HANSEI|AUTOEXAMEN / REFLEXIÓN
～省|～しょう|SHOU|MINISTERIO DE...
省エネ|しょうエネ|SHOUENE|AHORRO DE ENERGÍA
省く|はぶく|HABUKU|ELIMINAR / OMITIR
省略|しょうりゃく|SHOURYAKU|ABREVIACIÓN / OMISIÓN
了承|りょうしょう|RYOUSHOU|CONSENTIMIENTO / APROBACIÓN
承認|しょうにん|SHOUNIN|APROBACIÓN / CONFIRMACIÓN
承知|しょうち|SHOUCHI|CONOCIMIENTO / CONSENTIMIENTO
承る|うけたまわる|UKETAMAWARU|ATENDER / RECIBIR / SERVIR (HUMILDE)
展覧会|てんらんかい|TENRANKAI|EXPOSICIÓN / EXHIBICIÓN
展示|てんじ|TENJI|EXPOSICIÓN / EXHIBICIÓN / MUESTRA
～展|～てん|TEN|...EXPOSICIÓN
発展|はってん|HATTEN|DESARROLLO
破格|はかく|HAKAKU|EXCEPCIONAL
破産|はさん|HASAN|BANCARROTA / QUIEBRA
破片|はへん|HAHEN|FRAGMENTO / TROZO
破れる|やぶれる|YABURERU|ROMPERSE / RASGARSE
破る|やぶる|YABURU|ROMPER / RASGAR / VIOLAR (UNA REGLA)
処理|しょり|SHORI|PROCESAMIENTO / DISPOSICIÓN / TRÁMITE
処置|しょち|SHOCHI|GESTIÓN / MEDIDA / TRATAMIENTO
処分|しょぶん|SHOBUN|DISPOSICIÓN / CASTIGO / ELIMINACIÓN
温泉|おんせん|ONSEN|AGUAS TERMALES
泉|いずみ|IZUMI|MANANTIAL / FUENTE
宿題|しゅくだい|SHUKUDAI|DEBERES / TAREA
下宿|げしゅく|GESHUKU|ALOJAMIENTO / PENSIÓN
宿|やど|YADO|POSADA / ALBERGUE
季節|きせつ|KISETSU|ESTACIÓN DEL AÑO
四季|しき|SHIKI|LAS CUATRO ESTACIONES
冬季|とうき|TOUKI|TEMPORADA DE INVIERNO
豊作|ほうさく|HOUSAKU|COSECHA ABUNDANTE
豊かな|ゆたかな|YUTAKANA|RICO / ABUNDANTE
豊富（な）|ほうふ（な）|HOUFU|ABUNDANTE
富士山|ふじさん|FUJISAN|MONTE FUJI
富む|とむ|TOMU|SER RICO / ABUNDANTE EN
富|とみ|TOMI|RIQUEZA
送迎|そうけい|SOUKEI|SERVICIO DE RECOGIDA Y TRASLADO
歓迎|かんげい|KANGEI|BIENVENIDA
迎える|むかえる|MUKAERU|IR A RECOGER / RECIBIR / ACOGER
出迎え|でむかえ|DEMUKAE|IR AL ENCUENTRO DE ALGUIEN
～泊|～はく|HAKU|... NOCHES DE ESTADÍA
宿泊|しゅくはく|SHUKUHAKU|ALOJAMIENTO / HOSPEDAJE
泊まる|とまる|TOMARU|HOSPEDARSE / ALOJARSE
入居|にゅうきょ|NYUUKYO|MUDARSE A UN APARTAMENTO
居間|いま|IMA|SALA DE ESTAR
居眠り|いねむり|INEMURI|CABECEAR / QUEDARSE DORMIDO
居る|いる|IRU|ESTAR / EXISTIR (PARA SERES VIVOS)
築～年|ちく～ねん|CHIKUNEN|CONSTRUIDO EN EL AÑO...
建築|けんちく|KENCHIKU|ARQUITECTURA
三角|さんかく|SANKAKU|TRIÁNGULO
角度|かくど|KAKUDO|ÁNGULO
方角|ほうがく|HOUGAKU|DIRECCIÓN / RUMBO
角|かど|KADO|ESQUINA
生徒|せいと|SEITO|ESTUDIANTE / ALUMNO
徒歩|とほ|TOHO|A PIE / CAMINANDO
畳|たたみ|TATAMI|TATAMI (ESTERILLA DE PAJA JAPONESA)
畳む|たたむ|TATAMU|DOBLAR (ROPA, ETC.)
～畳|～じょう|JOU|... MEDIDA EN TATAMIS
欧米|おうべi|OUBEI|EUROPA Y AMÉRICA / OCCIDENTE
平米|へいべい|HEIBEI|METROS CUADRADOS
新米|しんまい|SHINMAI|ARROZ NUEVO / NOVATO
米|こめ|KOME|ARROZ (GRANO)
解説|かいせつ|KAISETSU|EXPLICACIÓN / COMENTARIO
解決|かいけつ|KAIKETSU|SOLUCIÓN / RESOLUCIÓN
解放|かいほう|KAIHOU|LIBERACIÓN / LIBERTAD
解散|かいさん|KAISAN|DISOLUCIÓN / DISPERSIÓN
解約|かいやく|KAIYAKU|CANCELACIÓN (DE UN CONTRATO)
解く|とく|TOKU|RESOLVER / DESATAR
この辺|このへん|KONOHEN|POR AQUÍ / ESTA ZONA
周辺|しゅうへん|SHUUHEN|ALREDEDORES / VECINDARIO
辺り|あたり|ATARI|ALREDEDOR / ENTORNO
海辺|うみべ|UMIBE|PLAYA / COSTA
警察|けいさつ|KEISATSU|POLICÍA
診察|しんさつ|SHINSATSU|CONSULTA MÉDICA
役所|やくしょ|YAKUSHO|OFICINA GUBERNAMENTAL / AYUNTAMIENTO
役目|やくめ|YAKUME|ROL / DEBER / FUNCIÓN
役者|やくしゃ|YAKUSHA|ACTOR / ACTRIZ
現役|げんえき|GENEKI|SERVICIO ACTIVO
美人|びじん|BIJIN|MUJER HERMOSA
美容|びよう|BIYOU|TRATAMIENTO DE BELLEZA
美しい|うつくしい|UTSUKUSHII|HERMOSO / BELLO
美術|びじゅつ|BIJUTSU|BELLAS ARTES
技術|ぎじゅつ|GIJUTSU|TÉCNICA / TECNOLOGÍA
手術|しゅじゅつ|SHUJUTSU|CIRUGÍA / OPERACIÓN
芸術|げいじゅつ|GEIJUTSU|ARTE
坂|さか|SAKA|COLINA / CUESTA
～坂|～ざか|ZAKA|... COLINA / ... CUESTA
～寺|～じ|JI|TEMPLO...
寺院|じいん|JIIN|TEMPLO / ABADÍA
寺|てら|TERA|TEMPLO
湾|わん|WAN|BAHÍA
～湾|～わん|WAN|BAHÍA DE...
～島|～とう|TOU|ISLA...
半島|はんとう|HANTOU|PENÍNSULA
列島|れっとう|RETTOU|ARCHIPIÉLAGO
島|しま|SHIMA|ISLA
海岸|かいがん|KAIGAN|COSTA / LITORAL
湾岸|わんがん|WANGAN|GOLFO / COSTA DE LA BAHÍA
岸|きし|KISHI|ORILLA / RIBERA
川岸|かわぎし|KAWAGISHI|ORILLA DEL RÍO
公園|こうえん|KOUEN|PARQUE
動物園|どうぶつえん|DOUBUTSUEN|ZOOLÓGICO
遊園地|ゆうえんち|YUENCHI|PARQUE DE ATRACCIONES
～園|～えん|EN|... PARQUE
～湖|～こ|KO|LAGO...
湖|みずうみ|MIZUUMI|LAGO
～城|～じょう|JOU|CASTILLO...
城|しろ|SHIRO|CASTILLO
渓谷|けいこく|KEIKOKU|DESFILADERO / BARRANCO
谷|たに|TANI|VALLE
谷間|たにま|TANIMA|VALLE / VAGUADA
谷川|たにがわ|TANIGAWA|ARROYO DE MONTAÑA
財産|ざいさん|ZAISAN|PROPIEDAD / FORTUNA
文化財|ぶんかざい|BUNKAZAI|BIEN CULTURAL / PATRIMONIO CULTURAL
財布|さいふ|SAIFU|CARTERA / BILLETERA
観光|かんこう|KANKOU|TURISMO / TURISMO RECEPTIVO
観客|かんきゃく|KANKYAKU|ESPECTADOR / AUDIENCIA
観察|かんさつ|KANSATSU|OBSERVACIÓN
観音|かんのん|KANNON|KANNON (DEIDAD BUDISTA DE LA MISERICORDIA)
宝石|ほうせき|HOUSEKI|JOYA / GEMA
宝物館|ほうもつかん|HOUMOTSUKAN|MUSEO DE TESOROS
国宝|こくほう|KOKUHOU|TESORO NACIONAL
宝物|たからもの|TAKARAMONO|TESORO
仏教|ぶっきょう|BUKKYOU|BUDISMO
仏像|ぶつぞう|BUTSUZOU|ESTATUA DE BUDA
仏|ほとけ|HOTOKE|BUDA / PERSONA FALLECIDA
日仏|にちふつ|NICHIFUTSU|JAPÓN Y FRANCIA
国王|こくおう|KOKUOU|REY
王子|おうじ|OUJI|PRÍNCIPE
王女|おうじょ|OUJO|PRINCESA
女王|じょおう|JOOU|REINA
銅|どう|DOU|COBRE / BRONCE
銅像|どうぞう|DOUZOU|ESTATUA DE BRONCE
塔|とう|TOU|TORRE / PAGODA
五重の塔|ごじゅうのとう|GOJUUNOTOU|PAGODA DE CINCO PISOS
～塔|～とう|TOU|... PAGODA / ... TORRE
絵|え|E|DIBUJO / PINTURA / CUADRO
絵の具|えのぐ|ENOGU|PINTURAS / ACUARELAS / COLORES
絵画|かいが|KAIGA|PINTURA (OBRA)
略|りゃく|RYAKU|ABREVIACIÓN
略す|りゃくす|RYAKUSU|ABREVIAR
省略|しょうりゃく|SHOURYAKU|ABREVIACIÓN / COMPENDIO
略歴|りゃくれき|RYAKUREKI|PERFIL / BREVE BIOGRAFÍA
順|じゅん|JUN|ORDEN
順路|じゅんろ|JUNRO|RUTA / ITINERARIO
順番|じゅんばん|JUNBAN|TURNO / ORDEN
順調|じゅんちょう|JUNCHOU|SIN CONTRATIEMPOS / FAVORABLE
出版|しゅっぱん|SHUPPAN|PUBLICACIÓN
出版社|しゅっぱんしゃ|SHUPPANSHA|EDITORIAL / COMPAÑÍA PUBLICADORA
版画|はんが|HANGA|GRABADO / ESTAMPA
芸術|げいじゅつ|GEIJUTSU|ARTE
工芸|こうげi|KOUGEI|ARTES INDUSTRIALES / ARTESANÍA
芸能|げいのう|GEINOU|ESPECTÁCULOS PÚBLICOS / ARTES ESCÉNICAS
園芸|えんげい|ENGEI|JARDINERÍA
複製|ふくせい|FUKUSEI|DUPLICADO / RÉPLICA
複雑（な）|ふくざつ|FUKUZATSU|COMPLEJO / COMPLICADO
複写|ふくしゃ|FUKUSHA|DUPLICADO / COPIA
複数|ふくすう|FUKUSUU|PLURAL / VARIOS
刊行物|かんこうぶつ|KANKOUBUTSU|PUBLICACIÓN
朝刊|ちょうかん|CHOUKAN|PERIÓDICO MATUTINO
週刊|しゅうかん|SHUUKAN|PUBLICACIÓN SEMANAL
月刊|げっかん|GEKKAN|PUBLICACIÓN MENSUAL
高層|こうそう|KOUSOU|LAS CAPAS SUPERIORES / ALTAS CAPAS
低層|ていそう|TEISOU|LAS CAPAS INFERIORES / BAJAS CAPAS
一層|いっそう|ISSOU|MÁS / AÚN MÁS
約束|やくそく|YAKUSOKU|PROMESA / CITA
束|たば|TABA|MANOJO / RAMO / PAQUETE
花束|はなたば|HANATABA|RAMO DE FLORES
束ねる|たばねる|TABANERU|ATAR EN UN MANOJO / ATAR APRETADO
甘い|あまい|AMAI|DULCE
甘口|あまくち|AMAKUCHI|SABOR DULCE / LADO DULCE (EN COMIDA/VINO)
甘かす|あまやかす|AMAYAKASU|MIMAR / CONSENTIR (A UN NIÑO)
辛い|からい|KARAI|PICANTE
辛口|からくち|KARAKUCHI|SABOR SECO / LADO PICANTE/SECO (EN COMIDA/VINO)
皿|さら|SARA|PLATO
～皿|～さら|SARA|... PLATOS (CONTADOR)
大皿|おおざら|OOZARA|PLATO GRANDE
小皿|こざら|KOZARA|PLATO PEQUEÑO
綿|めん|MEN|ALGODÓN
木綿|もめん|MOMEN|ALGODÓN / TELA DE ALGODÓN
綿|わた|WATA|ALGODÓN (PLANTA / EN BRUTO)
旧館|きゅうかん|KYUUKAN|EL EDIFICIO ANTIGUO
旧姓|きゅうせい|KYUUSEI|APELLIDO DE SOLTERA
復旧|ふっきゅう|FUKKYUU|RESTAURACIÓN / RECUPERACIÓN
厚生労働省|こうせいろうどうしょう|KOUSEIROUDOUSHOU|MINISTERIO DE SALUD, TRABAJO Y BIENESTAR
厚い|あつい|ATSUI|GRUESO
厚切り|あつぎり|ATSUGIRI|REBANADA GRUESA
厚かましい|あつかましい|ATSUKAMASHII|DESVERGONZADO / IMPUDENTE
厚手|あつで|ATSUDE|ARTÍCULO DE CONFECCIÓN GRUESA
薄い|うすい|USUI|DELGADO (MATERIAL) / CLARO (COLOR) / DEBIL (BEBIDA)
薄切り|うすぎり|USUGIRI|REBANADA DELGADA
薄手|うすで|USUDE|ARTÍCULO DE CONFECCIÓN DELGADA
薄める|うすめる|USUMERU|DILUIR / REBAJAR
粒|つぶ|TSUBU|GRANO / GOTA / PARTÍCULA
～粒|～つぶ|TSUBU|... GRANOS (CONTADOR)
北極|ほっきょく|HOKKYOKU|EL POLO NORTE
南極|なんきょく|NANKYOKU|EL POLO SUR
積極的|せっきょくてき|SEKKYOKUTEKI|ACTIVO / POSITIVO
消極的|しょうきょくてき|SHOUKYOKUTEKI|PASIVO / NEGATIVO
極|ごく|GOKU|MUY / EXTREMADAMENTE
改革|かいかく|KAIKAKU|REFORMA
革命|かくめい|KAKUMEI|REVOLUCIÓN
革|かわ|KAWA|CUERO
革製|かわせい|KAWASEI|HECHO DE CUERO
苦痛|くつう|KUTSUU|DOLOR / SUFRIMIENTO
苦い|苦い|NIGAI|AMARGO
苦しい|くるしい|KURUSHII|DOLOROSO / ANGUSTIOSO / DIFÍCIL
苦しむ|くるしむ|KURUSHIMU|SUFRIR / PADECER




// --- Frases del repertorio del Jefe (Se elegirán 2 al azar cada 1000 puntos) ---
//BOSS_FRAS|frase japonesa|Frase en Romaji|Traducción al español
BOSS_FRAS|消費税は商品に均等に課税される。|SHOUHIZEIHASHOUHINNIKINTOUNIKAZEISARERU|EL IMPUESTO AL CONSUMO SE APLICA POR IGUAL A LOS PRODUCTOS.
BOSS_FRAS|「広告が事実と異なり、納得がいかない場合はこちらにご連絡を。」|KOUKOKUGAJIJITSUTOKOTANARINATTOKUGAIKANAIBAAIWHAKOCHIRANIGORENRAKUWO|«SI EL ANUNCIO DIFIERE DE LOS HECHOS Y NO ESTÁ SATISFECHO, PÓNGASE EN CONTACTO CON NOSOTROS AQUÍ».
BOSS_FRAS|「〇〇ランドの入場者数がすでに百万人を超えました。」|RANDONONYUUJOUSHASUUGASUDENIHYAKUMANNINWOKOEMASHITA|«EL NÚMERO DE ASISTENTES A XX LAND YA HA SUPERADO EL MILLÓN DE PERSONAS».
BOSS_FRAS|世界で最も物価の高い都市はどこでしょう。|SEKAIDEMOTTOMOBUKKANOTAKAITOSHIHADOKODESHOU|¿CUÁL SERÁ LA CIUDAD CON EL COSTO DE VIDA MÁS ALTO DEL MUNDO?
BOSS_FRAS|子供を対象としたテレビ番組を制作する。|KODOMOWOTAISHOUTOSHITATEREBIBANGUMIWOSEISAKUSURU|PRODUCIR UN PROGRAMA DE TELEVISIÓN DIRIGIDO A LOS NIÑOS.
BOSS_FRAS|コレステロールの数値が上がっているので注意してください。|KORESUTEROURUNOSUUCHIGAAGATTEIRUNODECHUUISHITEKUDASAI|POR FAVOR, TENGA CUIDADO PORQUE SUS NIVELES DE COLESTEROL ESTÁN SUBIENDO.
BOSS_FRAS|雨靴は無いが、ぬれてもいい靴ならある。|AMAGUTSUHANAIGANURETEMOIIKUTSUNARAARU|NO TENGO BOTAS DE AGUA, PERO SÍ ZAPATOS QUE NO IMPORTA QUE SE MOJEN.
BOSS_FRAS|この番組は〇〇食品の提供でお送りしました。|KONOBANGUMIHASHOKUHINNOTEIKYOUDEOOKURISHIMASHITA|ESTE PROGRAMA FUE PRESENTADO POR CORTESÍA DE ALIMENTOS XX.
BOSS_FRAS|草花や野菜、果物などを箱に詰めて出荷する。|KUSABANAYAYASAIKUDAMONONADOWOHAKONITSUMETESHUKKASURU|EMPAQUETAR FLORES, VERDURAS, FRUTAS, ETC., EN CAJAS Y ENVIARLAS AL MERCADO.
BOSS_FRAS|その作業は単純だが、ミスをすると危険だ。|SONOSAGYOUHATANJUNDAGAMISUWOSURUTOKIKENDA|ESE TRABAJO ES SIMPLE, PERO ES PELIGROSO SI SE COMETE UN ERROR.
BOSS_FRAS|商品を使ったり作ったりして見せて売ることを実演販売という。|SHOUHINWOTSUKATTARITSUKUTTARISHITEMISETEURUKOTOWOJITSUENHANBAITOIU|VENDER UN PRODUCTO MOSTRANDO CÓMO SE USA O CÓMO SE HACE SE LLAMA VENTA CON DEMOSTRACIÓN EN VIVO.
BOSS_FRAS|年に２回、住民による地域の除草作業が行われる。|NENNINIKAIJUUMINNIYORUCHIIKINOJOSOUSAGYOUGAOKONAWARERU|DOS VECES AL AÑO, LOS RESIDENTES LLEVAN A CABO LABORES DE DESHIERBE EN LA REGIÓN.
BOSS_FRAS|事故処理中の道路に、まだ車の破片が散らばっている。|JIKOSHORICHUUNODOURONIMADAKURUMANOHAHENGACHIRABATTEIRU|EN LA CARRETERA DONDE SE ESTÁ ATENDIENDO EL ACCIDENTE, TODAVÍA HAY FRAGMENTOS DE COCHE ESPARCIDOS.
BOSS_FRAS|贈り物の包装は指示カウンターで承ります。|OKURIMONONOHOUSOUHASHIJIKAUNTAADEUKETAMAWARIMASU|NOS ENCARGAMOS DEL ENVOLTORIO DE REGALOS EN EL MOSTRADOR DE SERVICIO.
BOSS_FRAS|省エネというのはエネルギーを節約することです。|SHOUENETOIUNOHAENERUGIIWOSETSUYAKUSURUKOTODESU|AHORRO DE ENERGÍA SIGNIFICA ECONOMIZAR ENERGÍA.
BOSS_FRAS|あのお相撲さんは現役を引退して解説者になるそうだ。|ANOOSUMOUSANHAGENEKIWOINTAISHITEKAISETSUSHANINARUSOUDA|DICEN QUE AQUEL LUCHADOR DE SUMO SE RETIRARÁ DEL SERVICIO ACTIVO PARA CONVERTIRSE EN COMENTARISTA.
BOSS_FRAS|週末は富士山の近くの温泉宿に泊まる予定です。|SHUUMATSUHAFUJISANNOCHIKAKUNOONSENYADONITOMARUYOTEIDESU|ESTE FIN DE SEMANA TENGO PLANEADO HOSPEDARME EN UNA POSADA DE AGUAS TERMALES CERCA DEL MONTE FUJI.
BOSS_FRAS|冬季オリンピック選手の帰国を空港でお出迎える。|TOUKIORINPIKKUSENSHUNOKIKOKUWOKUUKOUDEODEMUKAERU|RECIBIR EN EL AEROPUERTO A LOS ATLETAS DE LOS JUEGOS OLÍMPICOS DE INVIERNO QUE REGRESAN A CASA.
BOSS_FRAS|この町は自然に囲まれた緑豊かなところです。|KONOMACHIHASHIZENNIKAKOMARETAMIDORIYUTAKANATOKORODESU|ESTE PUEBLO ES UN LUGAR RODEADO DE NATURALEZA Y MUY RICO EN VEGETACIÓN.
BOSS_FRAS|明日から１泊２日の旅行に行きます。|ASHITAKARAIPPAKUFUTSUKANORYOKOUNIIKIMASU|A PARTIR DE MAÑANA IRÉ A UN VIAJE DE DOS DÍAS Y UNA NOCHE.
BOSS_FRAS|様々な角度からアプローチして問題を解決する。|SAMAZAMANAKAKUDOKARAAPROUCHISHITEMONDAIWOKAIKETSUSURU|ABORDAR EL PROBLEMA DESDE VARIOS ÁNGULOS PARA RESOLVERLO.
BOSS_FRAS|居間と食堂を合わせて１２畳です。|IMATOSHOKUDOUWOAWASETEJUUNIJOUDESU|LA SALA DE ESTAR Y EL COMEDOR JUNTOS MIDEN DOCE TATAMIS.
BOSS_FRAS|私は大学で建築の勉強をしています。|WATASHIHADAIGAKUDEKENCHIKUNOBENKYOUWOSHITEIMASU|ESTOY ESTUDIANDO ARQUITECTURA EN LA UNIVERSIDAD.
BOSS_FRAS|お金が必要になったので、定期預金を解約する。|OKANEGAHITSUYOUNINATTANODETEIKIYOKINWOKAIYAKUSURU|COMO NECESITABA DINERO, CANCELÉ MI DEPÓSITO A PLAZO FIJO.
BOSS_FRAS|この坂を上ると美しいお寺がありますよ。|KONOSAKAWONOBORUTOUTSUKUSHIIOTERAGAARIMASUYO|SI SUBES ESTA CUESTA, ENCONTRARÁS UN TEMPLO HERMOSO.
BOSS_FRAS|市役所は警察署の向かいにあります。|SHIYAKUSHOHAKEISATSUSHONOMUKAINIARIMASU|EL AYUNTAMIENTO ESTÁ ENFRENTE DE LA COMISARÍA DE POLICÍA.
BOSS_FRAS|日本に科学技術を学ぶために来ました。|NIHONNIKAGAKUGIJUTSUWOMANABUTAMENIKIMASHITA|VINE A JAPÓN PARA ESTUDIAR CIENCIA Y TECNOLOGÍA.
BOSS_FRAS|湖の岸に白鳥がたくさんいるのが見える。|MIZUUMINOKISHINIHAKUCHOUGATAKUSANIRUNOGAMIERU|SE PUEDE VER QUE HAY MUCHOS CISNES EN LA ORILLA DEL LAGO.
BOSS_FRAS|日本列島を北から南まで旅行してみたい。|NIHONRETTOUWOKITAKARAMINAMIMADERYOKOUSHITEMITAI|ME GUSTARÍA VIAJAR POR EL ARCHIPIÉLAGO JAPONÉS DESDE EL NORTE HASTA EL SUR.
BOSS_FRAS|この公園の中に、お城や植物園があります。|KONOKOUENONAKANIOSHIROYASHOKUBUTSUENGAARIMASU|DENTRO DE ESTE PARQUE HAY UN CASTILLO Y UN JARDÍN BOTÁNICO.
BOSS_FRAS|海岸には波で打ち寄せられたごみが落ちていた。|KAIGANNIHANAMIDEUCHIYOSERARETAGOMIGAAOCHITEITA|EN LA COSTA HABÍA BASURA QUE HABÍA SIDO ARRASTRADA POR LAS OLAS.
BOSS_FRAS|このツアーの観光コースにパリのエッフェル塔も入っています。|KONOTUAANOKANKOUKOUSUNIPARINOEFFERUTOUMOHAITTEIMASU|EL CONTEXTO TURÍSTICO DE ESTE VIAJE TAMBIÉN INCLUYE LA TORRE EIFFEL DE PARÍS.
BOSS_FRAS|この建物は国宝に指定されています。|KONOTATEMONOHAKOKUHOUNISHITEISARETEIMASU|ESTE EDIFICIO ESTÁ DECLARADO TESORO NACIONAL.
BOSS_FRAS|渋谷駅の犬の銅像の前で待ち合わせしましょう。|SHIBUYAEKINOINUNODOUZOUNOMAEDEMACHIAWASESHIMASHOU|QUEDEMOS EN LA ESTACIÓN DE SHIBUYA, FRENTE A LA ESTATUA DE BRONCE DEL PERRO.
BOSS_FRAS|あの国には３人の王子がいます。|ANOKUNINIHAASANNINNOOUJIGAIMASU|EN AQUEL PAÍS HAY TRES PRÍNCIPES.
BOSS_FRAS|有名な絵画の複製を部屋にかざる。|YUUMEINAKAIGANOFUKUSEIWOHEYANIKAZARU|DECORAR LA HABITACIÓN CON UNA RÉPLICA DE UNA PINTURA FAMOSA.
BOSS_FRAS|これに関する説明は複雑なため、ここでは省略します。|KORENIKANSURUSETSUMEIHAFUKUZATSUNATAMEKOKODEHASHOURYAKUSHIMASU|COMO LA EXPLICACIÓN SOBRE ESTO ES COMPLEJA, SE OMITIRÁ AQUÍ.
BOSS_FRAS|出版社の刊行物の案内を見て、注文する。|SHUPPANSHANOKANKOUBUTSUNOANNAIWOMITECHUUMONSURU|REVISAR EL CATÁLOGO DE PUBLICACIONES DE LA EDITORIAL Y HACER UN PEDIDO.
BOSS_FRAS|昨日、デパートでテレビによく出ている芸能人を見かけた。|KINOUDEPAATODETEREBINIYOKUDETEIRUGEINOUJINWOMIKAKETA|AYER EN LOS ALMACENES VI A UNA CELEBRIDAD QUE APARECE A MENUDO EN LA TELEVISIÓN.
BOSS_FRAS|バラを花束にすると一層甘い香りがする。|BARAWOHANATABANISURUTOISSOUAMAIKAORIGASURU|CUANDO SE HACE UN RAMO CON LAS ROSAS, SU FRAGANCIA DULCE ES AÚN MÁS INTENSA.
BOSS_FRAS|肌が弱い人は、綿のシャツを着るとよいでしょう。|HADAGAYOWAIHITOHAMENNOSHATSUWOKIRUTOYOIDESHOU|LAS PERSONAS CON PIEL SENSIBLE HARÍAN BIEN EN USAR CAMISAS DE ALGODÓN.
BOSS_FRAS|当店のスパゲティは一皿が２人前の量です。|TOUTENNOSUPAGETIIHAHITOSARAGANININMAENORYOUDESU|LOS ESPAGUETIS DE NUESTRO LOCAL TIENEN UNA CANTIDAD POR PLATO EQUIVALENTE A DOS RACIONES.
BOSS_FRAS|今は田中ですが、旧姓は林です。|IMAHATANAKADESUGAKYUUSEIHAHAYASHIDESU|AHORA SOY TANAKA, PERO MI APELLIDO DE SOLTERA ES HAYASHI.
BOSS_FRAS|「みそ汁、味が薄いから、今度からもう少し濃くして。」|MISOSHIRUAJIGAUSUIKARAKONDOKARAMOUSUKOSHIKOKUSHITE|«LA SOPA DE MISO TIENE UN SABOR MUY LIGERO, ASÍ QUE LA PRÓXIMA VEZ HAZLA UN POCO MÁS CONCENTRADA».
BOSS_FRAS|「一粒でお口の中がスッキリ、さわやか！〇〇キャンディー」|HITOTSUBUDEOKUCHINONAKAGASUKKIRISAWAYAKAKYANDII|«¡UN SOLO GRANO Y TU BOCA QUEDARÁ LIMPIA Y FRESCA! CARAMELOS XX»
BOSS_FRAS|「教育制度の改革に積極的に取り組もう！」|KYOUIKUSEIDONOKAIKAKUNISEKKYOKUTEKINITORIKUMOU|«¡TRABAJEMOS DE MANERA ACTIVA EN LA REFORMA DEL SISTEMA EDUCATIVO!»
BOSS_FRAS|フランス革命は1978年に起きた。|FURANSUKAKUMEIHA1978NENNIOKITA|LA REVOLUCIÓN FRANCESA OCURRIÓ EN EL AÑO 1978.
`.trim();