export const KANJI_SEMANA_5_RAW = `
傾向|けいこう|KEIKOU|TENDENCIA
傾く|かたむく|KATAMUKU|INCLINARSE / LADEARSE
傾ける|かたむける|KATAMUKERU|INCLINAR (ALGO)
横転|おうてん|OUTEN|VOLCAR / VOLCAMIENTO
横断歩道|おうだんほどう|OUDANHODOU|PASO DE PEATONES
横|よこ|YOKO|LADO / LATERAL
熱湯|ねっとう|NETTOU|AGUA HIRVIENDO
湯|ゆ|YU|AGUA CALIENTE
湯飲み|ゆのみ|YUNOMI|TAZA DE TÉ
湯気|ゆげ|YUGE|VAPOR
恐怖|きょうふ|KYOUFU|MIEDO / TERROR
恐ろしい|おそろしい|OSOROSHII|TEMIBLE / TERRIBLE
恐れ|おそれ|OSORE|MIEDO / RIESGO
恐れ入ります|おそれいります|OSOREIRIMASU|DISCULPE / PERDÓN
原料|げんりょう|GENRYOU|MATERIA PRIMA
原産|げんさん|GENSAN|ORIGEN / NATIVO
野原|のはら|NOHARA|CAMPO
原因|げんいん|GEN'IN|CAUSA
要因|よういん|YOUIN|FACTOR
位置|いち|ICHI|UBICACIÓN / LOCALIZACIÓN
装置|そうち|SOUCHI|DISPOSITIVO / APARATO
置く|おく|OKU|PONER / COLOCAR
物置|ものおき|MONOOKI|TRASTERO / ALMACÉN
寝室|しんしつ|SHINSHITSU|DORMITORIO
寝る|ねる|NERU|DORMIR
寝坊|ねぼう|NEBOU|DORMILÓN / LEVANTARSE TARDE
昼寝|ひるね|HIRUNE|SIESTA
熱|ねつ|NETSU|CALOR / FIEBRE
熱心(な)|ねっしん(な)|NESSHIN|ENTUSIASTA / ZELOSO
熱中|ねっちゅう|NETCHUU|MANÍA / PASIÓN / ENTUSIASMO
熱い|あつい|ATSUI|CALIENTE (AL TACTO)
燃焼|ねんしょう|NENSHOU|COMBUSTIÓN
焼く|やく|YAKU|ASAR / PARRILLA
焼ける|やける|YAKERU|QUEMARSE / HORNEARSE
接触|せっしょく|SESSHOKU|CONTACTO
感触|かんしょく|KANSHOKU|TACTO (SENTIDO DEL)
触れる|ふれる|FURERU|TOCAR / MENCIONAR
触る|さわる|SAWARU|TOCAR
灯油|とうゆ|TOUYU|QUEROSENO
灯台|とうだい|TOUDAI|FARO
蛍光灯|けいこうとう|KEIKOUTOU|LÁMPARA FLUORESCENTE
電灯|でんとう|DENTOU|LUZ ELÉCTRICA
石油|せきゆ|SEKIYU|PETRÓLEO
原油|げんゆ|GENYU|PETRÓLEO CRUDO
油断|ゆだん|YUDAN|NEGLIGENCIA / DESCUIDO
油|あぶら|ABURA|ACEITE
余分(な)|よぶん(な)|YOBUN|EXCESIVO / SOBRANTE
余計(な)|よけい(な)|YOKEI|EXCESIVO / INNECESARIO
余裕|よゆう|YOYUU|MARGEN (DE TIEMPO O DINERO)
余る|あまる|AMARU|SOBRAR
鳴る|なる|NARU|SONAR / CHIRRIAR
鳴らす|ならす|NARASU|HACER SONAR (CAMPANA)
怒鳴る|どなる|DONARU|GRITAR
鳴く|なく|NAKU|PIAR / CROAR / BALAR
訪問|ほうもん|HOUMON|VISITA
訪れる|おとずれる|OTOZURERU|VISITAR / LLEGAR (UN DÍA)
訪ねる|たずねる|TAZUNERU|VISITAR
呼吸|こきゅう|KOKYUU|RESPIRACIÓN
呼ぶ|よぶ|YOBU|LLAMAR / INVITAR
呼び出す|よびだす|YOBIDASU|LLAMAR / CONVOCAR
警官|けいかん|KEIKAN|POLICÍA
警備|けいび|KEIBI|SEGURIDAD
警察|けいさつ|KEISATSU|POLICÍA (CUERPO)
警報|けいほう|KEIHOU|ALARMA / ADVERTENCIA
予報|よほう|YOHOU|PRONÓSTICO
情報|じょうほう|JOUHOU|INFORMACIÓN
電報|でんぽう|DENPOU|TELEGRAMA
裏|うら|URA|REVERSO / DETRÁS
裏口|うらぐち|URAGUCHI|PUERTA TRASERA
裏切る|うらぎる|URAGIRU|TRAICIONAR
裏表|うらおもて|URAOMOTE|AMBOS LADOS
交差点|こうさてん|KOUSATEN|CRUCE / INTERSECCIÓN
差出人|さしだしにん|SASHIDASHININ|REMITENTE
差|さ|SA|DIFERENCIA
人差し指|ひとさしゆび|HITOSASHIYUBI|DEDO ÍNDICE
差別|さべつ|SABETSU|DISCRIMINACIÓN
接続|せつぞく|SETSUZOKU|CONEXIÓN
継続|けいぞく|KEIZOKU|CONTINUIDAD
続く|つづく|TSUZUKU|CONTINUAR
手続き|てつづき|TETSUZUKI|PROCEDIMIENTO
辞書|じしょ|JISHO|DICCIONARIO
辞典|じてん|JITEN|DICCIONARIO
辞表|じひょう|JIHYOU|CARTA DE RENUNCIA
辞める|やめる|YAMERU|DIMITIR / RETIRARSE
画面|がめん|GAMEN|PANTALLA
方面|ほうめん|HOUMEN|DIRECCIÓN
正面|しょうめん|SHOUMEN|FRENTE
面積|めんせき|MENSEKI|ÁREA (SUPERFICIE)
操作|そうさ|SOUSA|OPERACIÓN / MANIPULACIÓN
体操|たいそう|TAISOU|EJERCICIO / GIMNASIA
実行|じっこう|JIKKOU|PRÁCTICA / ACCIÓN
実験|じっけん|JIKKEN|EXPERIMENTO
事実|じじつ|ZIJITSU|HECHO
実|み|MI|FRUTA / NUEZ
実る|みのる|MINORU|DAR FRUTO
列|れつ|RETSU|LÍNEA / COLA
行列|ぎょうれつ|GYOURETSU|PROCESIÓN / FILA
列車|れっしゃ|RESSHA|TREN
列島|れっとう|RETTOU|ARCHIPIÉLAGO
召し上がる|めしあがる|MESHIAGARU|COMER (FORMA CORTÉS)
〜杯|〜はい|~HAI|CONTADOR DE TAZAS
乾杯|かんぱい|KANPAI|¡SALUD! (BRINDIS)
杯|さかずき|SAKAZUKI|COPA DE SAKE
沸騰|ふっとう|FUTTOU|EBULLICIÓN
沸く|わく|WAKU|HERVIR
沸かす|わかす|WAKASU|HERVIR (ALGO)
粉末|ふんまつ|FUNMATSU|POLVO
花粉|かふん|KAFUN|POLEN
小麦粉|こむぎこ|KOMUGIKO|HARINA DE TRIGO
粉|こな|KONA|POLVO / HARINA
月末|げつまつ|GETSUMATSU|FIN DE MES
末|すえ|SUE|EL FINAL
末っ子|すえっこ|SUEKKO|HIJO MENOR
栄養|えいよう|EIYOU|NUTRICIÓN
繁栄|はんえい|HAN'EI|PROSPERIDAD
栄える|さかえる|SAKAERU|PROSPERAR
賞|しょう|SHOU|PREMIO
賞金|しょうきん|SHOUKIN|PREMIO (DINERO)
賞品|しょうひん|SHOUHIN|PREMIO (OBJETOS)
賞味期限|しょうみきげん|SHOUMIKIGEN|FECHA DE CONSUMO PREFERENTE
金庫|きんこ|KINKO|CAJA FUERTE
車庫|しゃこ|SHAKO|GARAJE
冷蔵庫|れいぞうこ|REIZOUKO|REFRIGERADOR
製造|せいぞう|SEIZOU|FABRICACIÓN
改造|かいぞう|KAIZOU|CONVERSIÓN / ADAPTACIÓN
造る|つくる|TSUKURU|FABRICAR / HACER
費用|ひよう|HIYOU|GASTO / COSTE
〜費|〜ひ|~HI|GASTO / COSTE
消費|しょうひ|SHOUHI|CONSUMO
可|か|KA|ACEPTABLE / POSIBLE
不可|ふか|FUKA|INACEPTABLE
可能(な)|かのう(な)|KANOU|POSIBLE
可決|かけつ|KAKETSU|APROBACIÓN
秒|びょう|BYOU|SEGUNDO
自身|じしん|JISHIN|UNO MISMO
出身|しゅっしん|SHUSSHIN|ORIGEN (LUGAR)
身体|しんたい|SHINTAI|CUERPO
身長|しんちょう|SHINCHOU|ESTATURA
中身|なかみ|NAKAMI|CONTENIDO
刺身|さしみ|SASHIMI|SASHIMI
入浴|にゅうよく|NYUUYOKU|BAÑARSE
浴室|よくしつ|YOKUSHITSU|CUARTO DE BAÑO
海水浴|かいすいよく|KAISUIYOKU|BAÑO EN EL MAR
浴びる|あびる|ABIRU|DUCHARSE / EMPAPARSE
浴衣|ゆかた|YUKATA|YUKATA
目的|もくてき|MOKUTEKI|OBJETIVO / PROPÓSITO
具体的(な)|ぐたいてき(な)|GUTAITEKI|CONCRETO / ESPECÍFICO
〜的|〜てき|~TEKI|SUFIJO ADJETIVAL
的確(な)|てきかく(な)|TEKIKAKU|PRECISO / EXACTO
汗|あせ|ASE|SUDOR
医師|いし|ISHI|MÉDICO
教師|きょうし|KYOUSHI|PROFESOR
技師|ぎし|GISHI|INGENIERO
相談|そうだん|SOUDAN|CONSULTA
会談|かいだん|KAIDAN|CONFERENCIA / CHARLAS
冗談|じょうだん|JOUDAN|BROMA
乾燥|かんそう|KANSOU|SEQUEDAD
骨折|こっせつ|KOSSETSU|FRACTURA
折れる|おれる|ORERU|ROMPERSE
折る|おる|ORU|ROMPER / DOBLAR (ALGO)
名刺|めいし|MEISHI|TARJETA DE VISITA
刺激|しげき|SHIGEKI|ESTÍMULO
刺す|さす|SASU|APUÑALAR
刺さる|ささる|SASARU|SER ATRAVESADO / PINCHARSE
肩|かた|KATA|HOMBRO
肩書き|かたがき|KATAGAKI|TÍTULO / CARGO
腰痛|ようつう|YOUTSUU|DOLOR DE ESPALDA
腰|こし|KOSHI|CINTURA / CADERA
腰掛ける|こしかける|KOSHIKAKERU|SENTARSE
腰掛け|こしかけ|KOSHIKAKE|SILLA / ASIENTO
関節|かんせつ|KANSETSU|ARTICULACIÓN
調節|ちょうせつ|CHOUSETSU|AJUSTE
節約|せつやく|SETSUYAKU|AHORRO
節|ふし|FUSHI|NUDO (MADERA) / ARTICULACIÓN
神話|しんわ|SHINWA|MITO
神道|しんとう|SHINTOU|SHINTOÍSMO
神経|しんけい|SHINKEI|NERVIO
神社|じんじゃ|JINJA|SANTUARIO
神様|かみさま|KAMISAMA|DIOS
頭痛|ずつう|ZUTSUU|DOLOR DE CABEZA
苦痛|くつう|KUTSUU|DOLOR / SUFRIMIENTO
痛い|いたい|ITAI|DOLOROSO
痛む|いたむ|ITAMU|DOLER
防虫剤|ぼうちゅうざい|BOUCHUUZAI|INSECTICIDA (REPELENTE)
殺虫剤|さっちゅうざい|SACCHUUZAI|INSECTICIDA
虫|むし|MUSHI|INSECTO
虫歯|むしば|MUSHIBA|DIENTE CARIADO
歯科|しか|SHIKA|ODONTOLOGÍA
歯周病|ししゅうびょう|SHISHUUBYOU|ENFERMEDAD PERIODONTAL
歯医者|はいしゃ|HAISHA|DENTISTA
歯車|はぐるま|HAGURUMA|ENGRANAJE
予防|よぼう|YOBOU|PREVENCIÓN
消防|しょうぼう|SHOUBOU|EXTINCIÓN DE INCENDIOS
防止|ぼうし|BOUSHI|PREVENCIÓN
防ぐ|ふせぐ|FUSEGU|PREVENIR
磨く|みがく|MIGAKU|PULIR / CEPILLAR
歯磨き|はみがき|HAMIGAKI|CEPILLADO DE DIENTES
抜群|ばつぐん|BATSUGUN|DESTACADO / SIN RIVAL
抜ける|ぬける|NUKERU|CAERSE / FALTAR
抜く|ぬく|NUKU|EXTRAER / OMITIR
追い抜く|おいぬく|OINUKU|DEJAR ATRÁS / ADELANTAR
悩む|なやむ|NAYAMU|PREOCUPARSE
悩み|なやみ|NAYAMI|PREOCUPACIÓN
髪|かみ|KAMI|PELO
髪の毛|かみのけ|KAMINOKE|UN CABELLO
白髪|しらが|SHIRAGA|PELO BLANCO / CANAS
用途|ようと|YOUTO|USO
途中|とちゅう|TOCHUU|EN EL CAMINO
中途|ちゅうと|CHUUTO|A MEDIAS / INACABADO
途端|とたん|TOTAN|EN EL MOMENTO EN QUE
道具|どうぐ|DOUGU|HERRAMIENTA
具合|ぐあい|GUAI|CONDICIÓN / ESTADO
家具|かぐ|KAGU|MUEBLES
雨具|あまぐ|AMAGU|EQUIPO DE LLUVIA
起床|きしょう|KISHOU|DESPERTARSE
床|ゆか|YUKA|SUELO
床屋|とこや|TOKOYA|PELUQUERÍA / BARBERÍA
床の間|とこのま|TOKONOMA|TOKONOMA
壁|かべ|KABE|PARED
乾電池|かんでんち|KANDENCHI|PILA SECA
乾く|かわく|KAWAKU|SECARSE
乾かす|かわかす|KAWAKASU|SECAR (ALGO)
毛布|もうふ|MOUFU|MANTA
分布|ぶんぷ|BUNPU|DISTRIBUCIÓN
座布団|ざぶとん|ZABUTON|COJÍN JAPONÉS
布|ぬの|NUNO|TELA
電柱|でんちゅう|DENCHUU|POSTE TELEGRÁFICO
柱|はしら|HASHIRA|PILAR / COLUMNA
溶岩|ようがん|YOUGAN|LAVA
溶ける|とける|TOKERU|DISOLVERSE / DERRETIRSE
溶かす|とかす|TOKASU|DISOLVER / DERRETIR
洗濯|せんたく|SENTAKU|LAVADO
洗濯機|せんたくき|SENTAKUKI|LAVADORA
直接|ちょくせつ|CHOKUSETSU|DIRECTO
間接|かんせつ|KANSETSU|INDIRECTO
面接|めんせつ|MENSETSU|ENTREVISTA
接近|せっきん|SEKKIN|PROXIMIDAD
塗る|ぬる|NURU|PINTAR / UNTAR
一緒|いっしょ|ISSHO|JUNTOS
泥|どろ|DORO|BARRO
泥棒|どろぼう|DOROBOU|LADRÓN
卵黄|らんおう|RAN'OU|YEMA DE HUEVO
黄身|きみ|KIMI|YEMA
黄色|きいろ|KIIRO|AMARILLO
羊毛|ようもう|YOUMOU|LANA
毛|け|KE|PELO / PLUMA / LANA
毛皮|けがわ|KEGAWA|PIEL / PELAJE
糸|いと|ITO|HILO
毛糸|けいと|KEITO|LANA (HILO)
肌|はだ|HADA|PIEL
肌着|はだぎ|HADAGI|ROPA INTERIOR
柔軟(な)|じゅうなん(な)|JUUAN|FLEXIBLE
柔道|じゅうどう|JUUDOU|JUDO
柔らかい|やわらかい|YAWARAKAI|SUAVE / TIERNO
香水|こうすい|KOUSUI|PERFUME
無香料|むこうりょう|MUKOURYOU|SIN FRAGANCIA
香辛料|こうしんりょう|KOUSHINRYOU|ESPECIAS
香り|かおり|KAORI|AROMA / OLOR
軟弱(な)|なんじゃく(な)|NANNJAKU|DÉBIL
柔軟体操|じゅうなんたいそう|JUUANTAISOU|EJERCICIOS DE CALENTAMIENTO
軟らかい|やわらかい|YAWARAKAI|SUAVE
// --- Frases del repertorio del Jefe (Se elegirán 2 al azar cada 1000 puntos) ---
//BOSS_FRAS|frase japonesa|Frase en Romaji|Traducción al español
BOSS_FRAS|正面玄関は閉まっていますから、裏口から入ってください。|SHOUMENGENKANWASHIMATTEIMASUKARAURAGUCHIKARAHATTEKUDASAI|La entrada principal está cerrada, así que, por favor, entre por la puerta trasera.
BOSS_FRAS|合格した人は入学手続きをしてください。|GOUKAKUSHITAHITOWANYUUGAKUTETSUZUKIOSHITEKUDASAI|Las personas que aprobaron, por favor, realicen los trámites de ingreso.
BOSS_FRAS|新製品を買いたい人の列が店の前から交差点まで続いている。|SHINSEIHINOKAITAIHITONORETSUGAMISENOMAEKARAKOUSATENMADETSUZUITEIRU|La fila de personas que quieren comprar el nuevo producto se extiende desde el frente de la tienda hasta el cruce.
BOSS_FRAS|私は課長に辞表を出した。|WATASHIWAKACHOUNIJIHYOUODASHITA|Presenté mi carta de renuncia al jefe de sección.
BOSS_FRAS|試験に出される問題の傾向を調べて受験勉強をする。|SHIKENNIDASARERUMONDAINOKEIKOUOSHIRABETEJUUKENBENKYOUSHURU|Estudio para el examen investigando las tendencias de las preguntas que van a aparecer.
BOSS_FRAS|「恐れ入りますが、荷物はそちらに置いてください。」|OSOREIRIMASUGANIMOTSUWASOCHIRANIOITEKUDASAI.|"Disculpe, por favor coloque su equipaje allí."
BOSS_FRAS|アフリカ原産のお茶を飲む。|AFURIKAGENSANNOOCHAONOMU|Bebo té de origen africano.
BOSS_FRAS|この車にはABSという安全装置がついています。|KONOKURUMANIWAABSTOIUANZENSOUTCHIGATSUITEIMASU|Este coche cuenta con un dispositivo de seguridad llamado ABS.
BOSS_FRAS|医師に相談したら的確な助言をしてくれた。|ISHINISOUDANSHITARATEKIKAKUNAJOGYONOSHITEKURETA|Consulté con el médico y me dio un consejo preciso.
BOSS_FRAS|指を折って数を数える。|YUBIOOTTEKAZUOKAZOERU.|Cuento los números doblando los dedos.
BOSS_FRAS|この洗濯機には乾燥機能も付いています。|KONOSENTAKUKINIWAKANSOUKINOUMOTSUITEIMASU|Esta lavadora también tiene función de secado.
BOSS_FRAS|～酒造というのは酒を製造している会社です。|SHUZOUTOIUNOWASAKEOSEIZOUSHITEIRUKAISHADESU|"~Shuzou" es una empresa que fabrica sake.
BOSS_FRAS|この試合の賞金の額は1位と2位とでは全然違う。|KONOSHIAINOSHOUKINNOGAKUWAICHIITONIITODEWAZENZENCHIGAU|El monto del premio en dinero de este torneo es totalmente diferente entre el primer y el segundo lugar.
BOSS_FRAS|「身長と体重をここに記入してください。」|SHINCHOUTOTAIJUUOKOKONIKINYUUSHITEKUDASAI|"Por favor, escriba aquí su estatura y su peso."
BOSS_FRAS|この電車は車庫に入りますので、ご乗車になれません。|KONODENSHAWASHAKONIHAIRIMASUNODEGOJOUSHANINAREMASEN|Este tren entra al garaje, por lo que no puede subir a él.
BOSS_FRAS|「開封後はなるべく早くお召し上がりください。」|KAIHOUGOWANARUBEKUHAYAKUOMESHIAGARIKUDASAI|"Después de abrirlo, por favor consúmalo lo antes posible."
BOSS_FRAS|「この町の発展と繁栄を願って、乾杯！」|KONOMACHINOHATTENTOHANEIONEGATTEKANPAI|¡Por el desarrollo y la prosperidad de esta ciudad, salud!
BOSS_FRAS|「年末年始は休業とさせていただきます。」|NENMATSUNENSHIWAKYUUGYOUTOSASETEITADAKIMASU|"Estaremos cerrados durante las fiestas de fin de año y año nuevo."
BOSS_FRAS|明日は花粉が多くなりそうです。ご注意ください。|ASHITAWAKAFUNGAOOKUNARISOUDESUGOCHUUIKUDASAI|Parece que mañana habrá mucho polen. Por favor, tenga cuidado.
BOSS_FRAS|訪問販売の人が何度も訪ねてきてチャイムを鳴らす。|HOUMONHANBAINOHITOGANANDOMOTAZUNETEKITECHAIMUONARASU|El vendedor a domicilio viene de visita muchas veces y toca el timbre.
BOSS_FRAS|台風が近づいて雨や風が強くなり、注意報が警報に変わった。|TAIFUUGACHIKAZUITEAMEYAKAZETSUYOKUNARICHUUIHOUGAKEIHOUNIKAWATTA|El tifón se acerca, la lluvia y el viento se han vuelto fuertes, y el aviso pasó a ser una alarma.
BOSS_FRAS|あの人の言動には裏表があって、信用できない。|ANOHITONOGENDOUNIWAURAOMOTEGAATTESHINYOUDEKINAI|Las palabras y acciones de esa persona son hipócritas (tienen doble cara), no se puede confiar en ella.
BOSS_FRAS|お客様にお呼び出しを申し上げます。|OKYAKUSAMANIOYOBIDASHIOMOUSHIAGEMASU|Hacemos un llamado a nuestros clientes.
`.trim();