export const KANJI_SEMANA_3_RAW = `
様子|ようす|YOUSU|ASPECTO / SITUACIÓN
同様|どうよう|DOUYOU|IGUAL / DE LA MISMA MANERA
～様|さま|SAMA|SUFIJO HONORÍFICO
様々な|さまざまな|SABAZAMANA|DIVERSOS / VARIOS
重要|じゅうよう|JUUYOU|IMPORTANTE
要点|ようてん|YOUTEN|PUNTO ESENCIAL
要約|ようやく|YOUYAKU|RESUMEN
要る|いる|IRU|NECESITAR
利用|りよう|RIYOU|USO / UTILIZACIÓN
便利|べんり|BENRI|CÓMODO / PRÁCTICO
金利|きんり|KINRI|TASA DE INTERÉS
有利|ゆうり|YUURI|VENTAJOSO
明細|めいさい|MEISAI|DETALLES
細かい|こまかい|KOMAKAI|FINO / MENUDO / PEQUEÑO
細い|ほそい|HOSOI|DELGADO / FINO
心細い|こころぼそい|KOKOROBOSOI|DESAMPARADO / SOLITARIO
在中|ざいちゅう|ZAICHUU|CONTIENE (EN SOBRES)
在学|ざいがく|ZAIGAKU|ESTAR MATRICULADO EN LA ESCUELA
現在|げんざい|GENZAI|ACTUALIDAD / EL PRESENTE
不在|ふざい|FUZAI|AUSENCIA
客席|きゃくせき|KYAKUSEKI|ASIENTO DE INVITADO / AUDITORIO
乗客|じょうきゃく|JOUKYAKU|PASAJERO
お客様|おきゃくさま|OKYAKUSAMA|CLIENTE (HONORÍFICO)
額|がく|GAKU|MARCO / CUADRO
金額|きんがく|KINGAKU|CANTIDAD DE DINERO
額|ひたい|HITAI|FRENTE
込む|こむ|KOMU|ESTAR CONGESTIONADO / LLENO
申し込む|もうしこむ|MOUSHIKOMU|SOLICITAR / INSCRIBIRSE
払い込む|ハライコム|HARAIKOMU|PAGAR (ENTREGA DE DINERO)
思い込む|おもいこむ|OMOIKOMU|ASUMIR / CREERSE ALGO
飛び込む|とびこむ|TOBIKOMU|ZAMBULLIRSE / SALTAR DENTRO
領収書|りょうしゅうしょ|RYOUSHUUSHO|RECIBO
～領|りょう|RYOU|TERRITORIO / DOMINIO
領事館|りょうじかん|RYOUJIKAN|CONSULADO
大統領|だいとうりょう|DAITOURYOU|PRESIDENTE
収入|しゅうにゅう|SHUUNYUU|INGRESOS
収集|しゅうしゅう|SHUUSHUU|RECOLECCIÓN / RECOGIDA
回収|かいしゅう|KAISHUU|RECUPERACIÓN / COBRO
吸収|きゅうしゅう|KYUUSHUU|ABSORCIÓN
収める|おさめる|OSAMERU|PAGAR / ENTREGAR
機械|きかい|KIKAI|MÁQUINA
器械体操|きかいたいそう|KIKAITAISOU|GIMNASIA CON APARATOS
曲|きょく|KYOKU|PIEZA MUSICAL / CANCIÓN
曲線|きょくせん|KYOKUSEN|LÍNEA CURVA
折り曲げる|おりまげる|ORIMAGERU|DOBLAR / TORCER
曲がる|まがる|MAGARU|GIRAR / DOBLARSE
汚染|おせん|OSEN|CONTAMINACIÓN
汚い|きたない|KITANAI|SUCIO
汚す|よごす|YOGOSU|ENSUCIAR
汚れる|よごれる|YOGORERU|ENSUCIARSE
殿様|とのさま|TONOSAMA|SEÑOR FEUDAL
～殿|どの|DONO|DON / DOÑA (TRATO FORMAL ESCRITO)
関連|かんれん|KANREN|RELACIÓN / CONEXIÓN
連続|れんぞく|RENZOKU|SERIE / CONTINUACIÓN
連休|れんきゅう|RENKYUU|DIAS FESTIVOS CONSECUTIVOS
連れる|つれる|TSURERU|ACOMPAÑAR
連絡|れんらく|RENRAKU|CONTACTO / COMUNICACIÓN
入荷|にゅうか|NYUUKA|RECEPCIÓN DE MERCANCÍAS
出荷|しゅっか|SHUKKA|ENVÍO / EMBARQUE
荷物|にもつ|NIMOTSU|EQUIPAJE / PAQUETE
届ける|とどける|TODOKERU|ENTREGAR / ENVIAR
届け出|とどけで|TODOKEDE|REPORTE / REGISTRO
届く|とどく|TODOKU|LLEGAR (EL CORREO / PAQUETE)
参考書|さんこうしょ|SANKOUSHO|LIBRO DE REFERENCIA
持参|じさん|JISAN|TRAER CONSIGO
参る|まいる|MAIRU|IR / VENIR (HUMILDE)
お参り|おまいり|OMAIRI|VISITA A UN SANTUARIO
衣類|いるい|IRUI|PRENDAS DE VESTIR / ROPA
衣料品|いりょうひん|IRYOUHIN|ARTÍCULOS DE ROPA
衣服|いふく|IFUKU|ROPA / VESTIDO
衣食住|いしょくじゅう|ISHOKUJUU|COMIDA, ROPA AND COBIJO
その他|そのた|SONOTA|OTROS / ADEMÁS
他人|たにん|TANIN|DESCONOCIDO / OTRA PERSONA
他方|たほう|TAHOU|POR OTRO LADO
全国|ぜんこく|ZENKOKU|TODO EL PAÍS
全～|ぜん|ZEN|TODO / EL CONJUNTO DE
完全な|かんぜんな|KANZENNA|PERFECTO / COMPLETO
全く|まったく|MATTAKU|COMPLETAMENTE / POR COMPLETO
全て|すべて|SUBETE|TODO
共通|きょうつう|KYOUTSUU|COMÚN / MUTUO
～と共に|とともに|TOTOMONI|JUNTO CON
忘年会|ぼうねんかい|BOUNENKAI|FIESTA DE FIN DE AÑO
忘れる|わすれる|WASURERU|OLVIDAR
忘れ物|わすれもの|WASUREMONO|OBJETO OLVIDADO
経過|けいか|KEIKA|TRANSCURSO / PROCESO
経験|けいけん|KEIKEN|EXPERIENCIA
経済|けいざい|KEIZAI|ECONOMÍA
経理|けいり|KEIRI|CONTABILIDAD
過去|かこ|KAKO|EL PASADO
通過|つうか|TSUUKA|PASO / TRÁNSITO
過ぎる|すぎる|SUGIRU|PASAR / EXCEDER
過ごす|すごす|SUGOSU|PASAR EL TIEMPO
責任|せきにん|SEKININ|RESPONSABILIDAD
責める|せめる|SEMERU|CULPAR / ACUSAR
担任|たんにん|TANNIN|TUTOR / PROFESOR ENCARGADO
任せる|まかせる|MAKASERU|ENCOMENDAR / ENCARGAR
負担|ふたん|FUTAN|CARGA / OBLIGACIÓN
負ける|まける|MAKERU|PERDER
負う|おう|OU|CARGAR / ASUMIR
必要|ひつよう|HITSUYOU|NECESARIO
必死|ひっし|HISSHI|DESESPERADO
必ず|かならず|KANARAZU|SIN FALTA / SEGURAMENTE
袋|ふくろ|FUKURO|BOLSA
手袋|てぶくろ|TEBUKURO|GUANTES
レジ袋|レジぶくろ|REJIBUKURO|BOLSA DEL SUPERMERCADO
足袋|たび|TABI|CALCETINES TRADICIONALES JAPONESES
ゴミ集積所|ゴミしゅうせきじょ|GOMISHUUSEKIJO|PUNTO DE RECOGIDA DE BASURA
面積|めんせき|MENSEKI|ÁREA / SUPERFICIE
積もる|つもる|TSUMORU|APILARSE / ACUMULARSE
積む|つむ|TSUMU|APILAR / CARGAR
燃料|ねんりょう|NENRYOU|COMBUSTIBLE
可燃|かねん|KANEN|INFLAMABLE / QUEMABLE
不燃|ふねん|FUNEN|INCOMBUSTIBLE / NO QUEMABLE
燃やせる|もやせる|MOYASERU|PERMITIR QUEMAR / QUEMABLE
枝|えだ|EDA|RAMA
小枝|こえだ|KOEDA|RAMITA / PALITO
紅葉|こうよう|KOUYOU|HOJAS DE OTOÑO
紅葉|もみじ|MOMIJI|MOMÍJI / ARCE JAPONÉS
葉|は|HA|HOJA
落ち葉|おちば|OCHIBA|HOJAS CAÍDAS
言葉|ことば|KOTOBA|PALABRA / IDIOMA
埋める|うめる|UMERU|ENTERRAR
埋め立てる|うめたてる|UMETATERU|RELLENAR TIERRA (RECLAMAR TIEMPO AL MAR)
埋まる|うまる|UMARU|ESTAR ENTERRADO
製品|せいひん|SEIHIN|PRODUCTO
～製|せい|SEI|HECHO EN / DE
内容|ないよう|NAIYOU|CONTENIDO
容器|ようき|YOUKI|RECIPIENTE / CONTENEDOR
美容|びよう|BIYOU|BELLEZA / CUIDADO ESTÉTICO
食器|しょっき|SHOKKI|VAJILLA
楽器|がっき|GAKKI|INSTRUMENTO MUSICAL
受話器|じゅわき|JUWAKI|AURICULAR DE TELÉFONO
器|うつわ|UTSUWA|RECIPIENTE / CAPACIDAD
包装|ほうそう|HOUSOU|EMPAQUETADO / ENVOLTORIO
新装開店|しんそうかいてん|SHINSOUKAITEN|REAPERTURA CON NUEVA DECORACIÓN
服装|ふくそう|FUKUSOU|VESTIMENTA / ROPA
衣装|いしょう|ISHOU|VESTUARIO / TRAJE
雑音|ざつおん|ZATSUON|RUIDO / INTERFERENCIA
雑用|ざつよう|ZATSUYOU|TAREAS VARIAS / MANDADOS
雑な|ざつな|ZATSUNA|MISCELÁNEO / DESCUIDADO
雑貨|ざっか|ZAKKA|ARTÍCULOS VARIOS
雑誌|ざっし|ZASSHI|REVISTA
日誌|にっし|NISSHI|DIARIO / REGISTRO DIARIO
資源|しげん|SHIGEN|RECURSOS
資料|しりょう|SHIRYOU|MATERIALES / DATOS
資金|しきん|SHIKIN|FONDOS / CAPITAL
避難|ひなん|HINAN|EVACUACIÓN
困難な|こんなんな|KONNANNA|DIFÍCIL
難しい|むずかしい|MUZUKASHII|DIFÍCIL
～し難い|しがたい|SHIGATAI|DIFÍCIL DE HACER
教訓|きょうくん|KYOUKUN|LECCIÓN / ENSEÑANZA
訓読み|くんよみ|KUNYOMI|LECTURA KUNYOMI
訓練|くんれん|KUNREN|ENTRENAMIENTO
練習|れんしゅう|RENSHUU|PRÁCTICA
地震|じしん|JISHIN|TERREMOTO
震える|ふるえる|FURUERU|TEMBLAR
参加|さんか|SANKA|PARTICIPACIÓN
加速|かそく|KASOKU|ACELERACIÓN
加える|くわえる|KUWAERU|AÑADIR / AGREGAR
加わる|くわわる|KUWAWARU|UNIRSE / PARTICIPAR
延期|えんき|ENKI|APLAZAMIENTO
延長|えんちょう|ENCHOU|EXTENSIÓN / PRÓRROGA
延びる|のびる|NOBIRU|PROLONGARSE / EXTENDERSE
延ばす|のばす|NOBASU|PROLONGAR / APLAZAR
断水|だんすい|DANSUI|CORTE DE AGUA
断定|だんてい|DANTEI|DECISIÓN / AFIRMACIÓN CONCLUYENTE
横断|おうだん|OUDAN|CRUCE
断る|ことわる|KOTOWARU|RECHAZAR
水道管|すいどうかん|SUIDOUKAN|TUBERÍA DE AGUA
管理|かんり|KANRI|GESTIÓN / ADMINISTRACIÓN
保管|にかん|HIKAN|CUSTODIA / GUARDADO
管|くだ|KUDA|TUBO / TUBERÍA
日記|にっき|NIKKI|DIARIO
記入|きにゅう|KINYUU|ANOTACIÓN / RELLENAR DATOS
記号|きごう|KIGOU|SÍMBOLO / SIGNO
下記|かき|KAKI|LO SIGUIENTE / ABAJO FIRMADO
記者|きしゃ|KISHA|PERIODISTA / REPORTERO
記事|きじ|KIJI|ARTÍCULO / NOTICIA
記す|しるす|SHIRUSU|ANOTAR / ESCRIBIR
迷惑|めいわく|MEIWAKU|MOLESTIA
迷信|めいしん|MEISHIN|SUPERSTICIÓN
迷う|まよう|MAYOU|PERDERSE
迷子|まいご|MAIGO|NIÑO PERDIDO
協力|きょうりょく|KYOURYOKU|COOPERACIÓN
協定|きょうてい|KYOUTEI|ACUERDO / PACTO
協会|きょうかい|KYOUKAI|ASOCIACIÓN
願書|がんしょ|GANSHO|SOLICITUD ESCRITA
願う|ねがう|NEGAU|DESEAR / PEDIR
平成|へいせい|HEISEI|ERA HEISEI
平日|へいじつ|HEIJITSU|DÍAS LABORABLES
平気な|へいきな|HEIKINA|CALMADO / INDIFERENTE
平等|びょうどう|BYOUDOU|IGUALDAD
平らな|たいらな|TAIRANA|PLANO / LLANO
平仮名|ひらがな|HIRAGANA|HIRAGANA
結果|けっか|KEKKA|RESULTADO
結局|けっきょく|KEKKYOKU|AL FIN Y AL CABO / DESPUÉS DE TODO
結ぶ|むすぶ|MUSUBU|ATAR / CONECTAR / CONCLUIR
効果|こうか|KOUKA|EFECTO
果実|かじつ|KAJITSU|FRUTA / FRUTO
果物|くだもの|KUDAMONO|FRUTA
果たす|はたす|HATASU|LLEVAR A CABO / CUMPLIR
開封|かいふう|KAIFUU|APERTURA DE UNA CARTA / DESPRECINTAR
封書|ふうしょ|FUUSHO|CARTA CERRADA / SELLADA
同封|どうふう|DOUFUU|ADJUNTO / INCLUIDO (EN UNA CARTA)
方法|ほうほう|HOUHOU|MÉTODO / FORMA
文法|ぶんぽう|BUNPOU|GRAMÁTICA
作法|さほう|SAHOU|MODALES / MANERAS
法人|ほうじん|HOUJIN|PERSONA JURÍDICA / CORPORACIÓN
各～|かく|KAKU|CADA / CADA UNO
各自|かくじ|KAKUJI|CADA UNO / RESPECTIVO
各地|かくち|KAKUCHI|TODAS PARTS / MUCHOS LUGARES
～各位|かくい|KAKUI|A QUIEN CORRESPONDA / ESTIMADOS TODOS
地位|ちい|CHII|ESTATUS / POSICIÓN SOCIAL
～位|い|I|PUESTO (USADO PARA CLASIFICACIONES)
位|くらい|KURAI|RANGO / POSICIÓN
異常な|いじょうな|IJOUNA|ANORMAL
同音異義語|どうおんいぎご|DOUONIGIGO|HOMÓNIMO
異変|いへん|IHEN|ACCIDENTE / SUCESO INUSUAL
異なる|ことなる|KOTONARU|DIFERIR / SER DIFERENTE
移転|いてん|ITEN|MUDANZA / TRASLADO
移動|いどう|IDOU|MOVIMIENTO / TRASLADO
移る|うつる|UTSURU|MUDARSE / TRASLADARSE
移す|うつす|UTSUSU|MOVER / TRASLADAR (ALGO)
事務|じむ|JIMU|TRABAJO DE OFICINA
事務所|じむしょ|JIMUSHO|OFICINA
任務|にんむ|NINMU|DEBER / TAREA / MISIÓN
務める|つめる|TSUTOMERU|TRABAJAR / SERVIR
変更|へんこう|HENKOU|CAMBIO / ALTERACIÓN
更新|こうしん|KOUSHIN|RENOVACIÓN
更衣室|こういしつ|KOUISHITSU|VESTUARIO / CAMBIADOR
引っ越す|ひっこす|HIKKOSU|MUDARSE DE CASA
乗り越す|のりこす|NORIKOSU|PASARSE DE ESTACIÓN
お越しの際|おこしのさい|OKOSHINOSAI|CUANDO VENGA
郊外|こうがい|KOUGAI|SUBURBIOS / AFUERAS
近郊|きんこう|KINKOU|ALREDEDORES / ENVIROS
円周|えんしゅう|ENSHUU|CIRCUNFERENCIA (DE UN CÍRCULO)
周り|まわり|MAWARI|ALREDEDOR / VECINDARIO
畑|ハタケ|HATAKE|CAMPO DE CULTIVO / HUERTO DE VERDURAS
花畑|はなばたけ|HANABATAKE|CAMPO DE FLORES


// --- Frases del repertorio del Jefe (Se elegirán 2 al azar cada 1000 puntos) ---
//BOSS_FRAS|frase japonesa|Frase en Romaji|Traducción al español
BOSS_FRAS|「お客様のおかけになった番号は現在使われておりません。」|OKYAKUSAMANIOKAKEINATTABANGOUHAALIZAITSUKAWRETEORIMASEN|“EL NÚMERO QUE HA MARCADO NO SE ENCUENTRA EN USO ACTUALMENTE”.
BOSS_FRAS|「細かいお金が要るんですが、両替してくれませんか。」|KOMAKAIOKANEGAIRUNDESUGARYOUGAESHITEKUREMASENKA|“NECESITO DINERO SUELTO, ¿NO PODRÍA CAMBIARME?”
BOSS_FRAS|「金利が低いときに、お金を借りたほうがいいですね。」|KINRIGAHIKUITOKINIOKANEWOKARITAHOUGAIIDESUNE|“ES MEJOR PEDIR PRESTADO DINERO CUANDO LAS TASAS DE INTERÉS ESTÁN BAJAS, ¿VERDAD?”
BOSS_FRAS|読んだ本の内容を要約する。|YONDAPONNONAIYOUWOYOUYAKUSURU|RESUMIR EL CONTENIDO DE UN LIBRO LEÍDO.
BOSS_FRAS|手紙のあて名にはふつう「様」を使います。|TEGAMINIOATENANIHAFUTSUUSAMAWOTSUKAIMASU|PARA EL DESTINATARIO DE UNA CARTA GENERALMENTE SE UTILIZA "SAMA".
BOSS_FRAS|「その信号を右に曲がってください。」|SONOSHINGOUWOMIGINIMAGATTEKUDASAI|“POR FAVOR, GIRE A LA DERECHA EN ESE SEMÁFORO”.
BOSS_FRAS|コンビニでも払い込みができるので便利だ。|KONBINIDEMOHARAIKOMUGADEKIRUNODEBENRIDA|ES CONVENIENTE PORQUE TAMBIÉN SE PUEDEN REALIZAR PAGOS EN LAS TIENDAS DE CONVENIENCIA.
BOSS_FRAS|ごみの収集は月・水・金です。|GOMINOSHUUSHUUHAMETSUSUIKINDESU|LA RECOGIDA DE BASURA ES LOS LUNES, MIÉRCOLES Y VIERNES.
BOSS_FRAS|5月の連休に両親を旅行に連れていく。|GOGATSUNORENKYUUNIRYOUSHINWORIOKOUINITSURETEIKU|LLEVARÉ A MIS PADRES DE VIAJE DURANTE LOS DÍAS FESTIVOS CONSECUTIVOS DE MAYO.
BOSS_FRAS|「会議に使いますから、この書類をコピーしてください。」|KAIGINITSUKAIMASUKARAKONOSHORUIWOKOPIISHITEKUDASAI|“COMO LOS VOY A USAR EN LA REUNIÓN, POR FAVOR FOTOCOPIE ESTOS DOCUMENTOS”.
BOSS_FRAS|教科書や参考書、その他必要な本を買う。|KYOUKASHOYASANKOUSHOZONOTAHITSUYOUNAHONWOKAU|COMPRAR LIBROS DE TEXTO, LIBROS DE REFERENCIA Y OTROS LIBROS NECESARIOS.
BOSS_FRAS|品物が入荷しましたら、電話でご連絡します。|SHINAMONGANYUUKASHIMASHITARADENWADELENRAKUSHIMASU|CUANDO LLEGUE LA MERCANCÍA, LE CONTACTAREMOS POR TELÉFONO.
BOSS_FRAS|着払い：受け取った人が送料を払う|CHAKUBARAIUKETOTTACITOGASOURYOUWOHARAU|PAGO EN DESTINO: LA PERSONA QUE RECIBE PAGA EL COSTO DE ENVÍO.
BOSS_FRAS|代金引換（＝代引）：受け取るとき品物の代金を払う|DAIKINHIKIKAEUKETORUTOKISHINAMONODAIKINWOHARAU|PAGO CONTRA REEMBOLSO: SE PAGA EL VALOR DEL ARTÍCULO AL MOMENTO DE RECIBIRLO.
BOSS_FRAS|「山の頂上でお弁当にしましょう。」|YAMANOTCHOUJOUDEOBENTOUNISHIMASHOU|“ALMORCÉMOS EL BENTO EN LA CIMA DE LA MONTAÑA”.
BOSS_FRAS|「今お配りしたプリントに作業の分担が書いてあります。」|IMAOKUBARISHITAPURINTOANISAGYOUAOBUNTANGAKAITEARIMASU|“EN EL IMPRESO QUE ACABO DE DISTRIBUIR ESTÁ ESCRITA LA DISTRIBUCIÓN DE LAS TAREAS”.
BOSS_FRAS|アイスクリームは冷蔵庫の冷凍室に入れます。|AISUKURIIMUHAREIZOUKONOREITOUSHITUNIIREMASU|EL HELADO SE COLOCA EN EL CONGELADOR DE LA REFRIGERADORA.
BOSS_FRAS|A＝Bとは、AはBと等しいという意味です。|ABTOHAHAHATOSHIIYUUIMIDESU|A=B SIGNIFICA QUE A ES IGUAL A B.
BOSS_FRAS|この薬は風邪によく効く。|KONOKUSURIHAKAZENIYOKUKIKU|ESTA MEDICINA ES MUY EFECTIVA PARA EL RESFRIADO.
BOSS_FRAS|外国の人たちと交流するのは楽しいです。|GAIKOKUNOHITOTACHITOKOURYUUSURUHUHATANOSHIIDESU|ES DIVERTIDO INTERCAMBIAR Y CONVIVIR CON PERSONAS EXTRANJERAS.
BOSS_FRAS|今までに一度も負けたことのない相手に負けてしまった。|IMAMADEINIICHIDOMOMAKETAKOTONOANIAITENIMAKETESHIMATTA|TERMINÉ PERDIENDO ANTE UN OPONENTE CONTRA EL QUE NUNCA ANTES HABÍA PERDIDO.
BOSS_FRAS|卵10個入りパック百円！お一人様1パック限り！|TAMAGOJUKKOIRIPAKKUHYAKUENOHITORISAMAIFFAKKUKAGIRI|¡PAQUETE DE 10 HUEVOS A 100 YENES! ¡LÍMITE DE UN PAQUETE POR PERSONA!
BOSS_FRAS|子どもの勉強のことは担任の先生にお任せしています。|KODOMONOBENKYOUNOKOTOHATANNINNOSENSEINIONAMAKASESHITEIMASU|DEJO LOS ASUNTOS DE ESTUDIO DE MI HIJO EN MANOS DE SU TUTOR.
BOSS_FRAS|この薬を飲んでください。1週間経過をみましょう。|KONOKUSURIWOWONDETEKUDASAIIFFUUKANKEIKAWOWIMASHOU|POR FAVOR, TOME ESTA MEDICINA. VEAMOS LA EVOLUCIÓN DURANTE UNA SEMANA.
BOSS_FRAS|仕事の量が多すぎる。社員の負担を軽くしなければならない。|SHIGOTONORYOUGAOOSUGIRUSHAIENNOFUTANWOKARUKUSHINAKELEBANARANAI|LA CANTIDAD DE TRABAJO ES EXCESIVA. SE DEBE ALIGERAR LA CARGA DE LOS EMPLEADOS.
BOSS_FRAS|このカードは全店共通でお使いになれます。|KONOKARDOCHAZENTENKYOUTSUUDEOTSUKAININAREMASU|ESTA TARJETA SE PUEDE UTILIZAR EN COMÚN EN TODAS LAS TIENDAS.
BOSS_FRAS|雪が積もって花だんが埋まってしまった。|YUKIGATSUMOTTEHANADANGAUMATTESHIMATTA|LA NIEVE SE ACUMULÓ Y EL JARDÍN DE FLORES QUEDÓ ENTERRADO.
BOSS_FRAS|落ち葉や木の枝は燃やせるゴミになります。|OCHIBAYAKINOEDAHAMOYASERUGOMININARIMASU|LAS HOJAS CAÍDAS Y LAS RAMAS DE LOS ÁRBOLES SE CONVIERTEN EN BASURA INCINERABLE.
BOSS_FRAS|この洗剤を使うときは必ずゴム手袋をしてください。|KONOSENZAIWOTSUKAUTOKIHANAKARAZUGOMUTEBUKUROWOSHITEKUDASAI|POR FAVOR, ASEGÚRESE DE USAR GUANTES DE GOMA CUANDO UTILICE ESTE DETERGENTE.
BOSS_FRAS|植物から自動車の燃料を作る。|SHOKUBUTSUKARAJIDOUSHANONENRYOUWOWOKURU|PRODUCIR COMBUSTIBLE PARA AUTOMÓVILES A PARTIR DE PLANTAS.
BOSS_FRAS|器がきれいだと、料理もおいしく見える。|UTSUWAGAKIREIDATORIOURIMOOISHIKUMIETSU|CUANDO EL RECIPIENTE ES HERMOSO, LA COMIDA TAMBIÉN SE VE DELICIOSA.
BOSS_FRAS|この時計はスイス製です。|KONOTOKEIHASUISUSEIDESU|ESTE RELOJ ESTÁ HECHO EN SUIZA.
BOSS_FRAS|雑音がひどくて電話がよく聞こえません。|ZATSUONGAHIDUKETEDENWAGAYOKUKIKOEMASEN|EL RUIDO DE INTERFERENCIA ES TAN FUERTE QUE NO PUEDO ESCUCHAR BIEN EL TELÉFONO.
BOSS_FRAS|この町ではリサイクルのため、第2土曜日に古新聞・古雑誌などを回収します。|KONOMACHIDEHARISAIKURUNOTAMEDAINIDOUYOUBINIFURUSHINBUNFURUZASSHINADOWOKAISHUUSHIMASU|EN ESTE PUEBLO, SE RECOGEN PERIÓDICOS Y REVISTAS VIEJAS EL SEGUNDO SÁBADO DE CADA MES PARA SU RECICLAJE.
BOSS_FRAS|この練習問題はあまり難しくない。|KONORENSHUUMONDAIHAAMARIMUZUKASHIKUNAI|ESTE PROBLEMA DE PRÁCTICA NO ES MUY DIFÍCIL.
BOSS_FRAS|「届かないので延長コードを持ってきてください。」|TODOKANAINODEENCHOUKORDOWOMOTTEKITEKUDASAI|“COMO NO ALCANZA, POR FAVOR TRAIGA UN CABLE DE EXTENSIÓN”.
BOSS_FRAS|「あ！地震だ！揺れてる！」|AJISHINDAYURETERU|“¡AH! ¡UN TERREMOTO! ¡ESTÁ TEMBLANDO!”
BOSS_FRAS|材料がやわらかくなったら、さとうを加えます。|ZAIRYOUGAYAWARAKAKUNATTARASATOUWOKUWAEMASU|CUANDO LOS INGREDIENTES SE ABLANDEN, SE AÑADE EL AZÚCAR.
BOSS_FRAS|迷惑メールが何通も届いて困っている。|MEIWAKUMAERUGANANTSUUMOTODASHTEKOMATTEIRU|ESTOY EN APUROS PORQUE ME LLEGAN MUCHOS CORREOS ELECTRÓNICOS DE SPAM.
BOSS_FRAS|平日のこの時間は道路が込んでいる。|HEIJITSUNOKONOJIKANHADOUROGAKONDEIRU|A ESTA HORA EN LOS DÍAS LABORABLES LA CARRETERA ESTÁ CONGESTIONADA.
BOSS_FRAS|「駐車お断り」|CHUUSHAOKOTOWARI|“PROHIBIDO ESTACIONAR”.
BOSS_FRAS|大学に入学願書を郵送する。|DAIGAKUNIINYUUGAKUGANSHOWOYUUSOUSURU|ENVIAR POR CORREO POSTAL LA SOLICITUD DE INGRESO A LA UNIVERSIDAD.
BOSS_FRAS|手紙に写真を同封する。|TEGAMINISHASHINWODOUFUUSURU|ADJUNTAR UNA FOTO EN LA CARTA.
BOSS_FRAS|最近、全国各地で異常な事件が起こっている。|SAIKINZENKOKUKAKUCHIDEIJOUNAJIKENGAOKOTTEIRU|RECIENTEMENTE, ESTÁN OCURRIENDO SUCESOS ANORMALES EN TODO EL PAÍS.
BOSS_FRAS|朝、果物を食べると体にいいそうだ。|ASAKADAMONOWOTABERUTOKARADANIIISOUDA|PARECE SER QUE ES BUENO PARA EL CUERPO COMER FRUTA POR LA MAÑANA.
BOSS_FRAS|運動靴のひもがほどけそうですよ。しっかり結んで。|UNDOUKUTSUNOHIMOGAHODOKESOUNESYOSHIKKARIMUSUNDE|LOS CORDONES DE TUS ZAPATOS DEPORTIVOS PARECEN ESTAR SUELTOS. ÁTALOS FIRMEMENTE.
BOSS_FRAS|会社の経理事務を担当しています。|KAISHANOKEIRIJIMUWOTANTOUSHITEIMASU|ESTOY A CARGO DE LAS LABORES DE CONTABILIDAD DE LA EMPRESA.
BOSS_FRAS|旅券事務所でパスポートの更新をする。|RYOKENJIMUSHODEPASUPOOTONOKOUSHINWOSURU|RENOVAR EL PASAPORTE EN LA OFICINA DE PASAPORTES.
BOSS_FRAS|女子更衣室は2階に移りました。|JOSHIKOUISHITSUHANIKAINIUTSURIMASHITA|EL VESTUARIO DE MUJERES SE TRASLADÓ AL SEGUNDO PISO.
BOSS_FRAS|引っ越した家の周りは緑が多い。|HIKKOSHITAIENOMAWARIHAMIDORIGAOOI|HAY MUCHA VEGETACIÓN ALREDEdor DE LA CASA A LA QUE ME MUDÉ.
`.trim();
