export const KANJI_SEMANA_4_RAW = `
署名|しょめい|SHOMEI|UNA FIRMA
部署|ぶしょ|BUSHO|PUESTO / ESTACIÓN
消防署|しょうぼうしょ|SHOUBOUSHO|UNA ESTACIÓN DE BOMBEROS
税務署|ぜいむしょ|ZEIMUSHO|OFICINA DE IMPUESTOS
依頼|いらい|IRAI|PETICIÓN / ENCOMIENDA
信頼|しんらい|SHINRAI|CONFIANZA
頼む|たのむ|TANOMU|PEDIR / SOLICITAR
頼もしい|たのもしい|TANOMOSHII|CONFIABLE / FIABLE
頼る|たよる|TAYORU|DEPENDER DE / CONTAR CON
頼りない|たよりない|TAYORINAI|IMPOTENTE / POCO FIABLE
都道府県|とどうふけん|TODOUFUKEN|PREFECTURAS DE JAPÓN
京都府|きょうとふ|KYOUTOFU|PREFECTURA DE KIOTO
到着|とうちゃく|TOUCHAKU|LLEGADA
希望|きぼう|KIBOU|ESPERANZA / DESEO
失望|しつぼう|SHITSUBOU|PÉRDIDA DE ESPERANZA / DESESPERACIÓN
望遠鏡|ぼうえんきょう|BOUENKYOU|UN TELESCOPIO
望む|ノぞむ|NOZOMU|QUERER / ESPERAR / DESEAR
申請|しんせい|SHINSEI|UNA SOLICITUD / APLICACIÓN
申す|もうす|MOUSU|DECIR (FORMA HUMILDE)
申し込み|もうしこみ|MOUSHIKOMI|SOLICITUD / PROPUESTA
申し上げる|もうしあげる|MOUSHIAGERU|DECIR (FORMA MUY HUMILDE)
姓|せい|SEI|APELLIDO FAMILIAR
姓名|せいめい|SEIMEI|NOMBRE COMPLETO
年齢|ねんれい|NENREI|EDAD
高齢|こうれい|KOUREI|EDAD AVANZADA / VEJEZ
男性|だんせい|DANSEI|UN HOMBRE
女性|じょせい|JOSEI|UNA MUJER
性別|せいべつ|SEIBETSU|SEXO / GÉNERO
性質|せいしつ|SEISHITSU|NATURALEZA / DISPOSICIÓN / CARÁCTER
安全性|あんぜんせい|ANZENSEI|SEGURIDAD
可能性|かのうせい|KANOUSEI|POSIBILIDAD
お宅|おたく|OTAKU|SU CASA / HOGAR (FORMA RESPETUOSA)
自宅|じたく|JITAKU|MI CASA / PROPIO HOGAR
住宅|じゅうたく|JUUTAKU|VIVIENDA / ALOJAMIENTO
帰宅|きたく|KITAKU|REGRESO A CASA
勤務|きんむ|KINMU|SERVICIO / DEBER / TRABAJO
出勤|しゅっきん|SHUKKIN|ASISTENCIA AL TRABAJO
通勤|つうきん|TSUUKIN|VIAJE AL TRABAJO / CONMUTACIÓN
勤める|つとめる|TSUTOMERU|TRABAJAR / ESTAR EMPLEADO
全部|ぜんぶ|ZENBU|TODO / POR COMPLETO
部分|ぶぶん|BUBUN|PARTE / PORCIÓN
部長|ぶちょう|BUCHOU|JEFE DE DEPARTAMENTO / GERENTE
学部|がくぶ|GAKUBU|UNA FACULTAD (UNIVERSITARIA)
部屋|へや|HEYA|UNA HABITACIÓN / CUARTO
結婚|けっこん|KEKKON|UN MATRIMONIO
婚約|こんやく|KONYAKU|UN COMPROMISO / COMPROMISO MATRIMONIAL
未婚|みこん|MIKON|SOLTERO / NO CASADO
新婚|しんこん|SHINKON|RECIÉN CASADO
招待|しょうたい|SHOUTAI|UNA INVITACIÓN
招く|まねく|MANEKU|INVITAR
～状|じょう|JOU|CARTA (E.G. DE INVITACIÓN)
現状|げんじょう|GENJOU|SITUACIÓN ACTUAL / ESTADO ACTUAL
状態|じょうたい|JOUTAI|UNA SITUACIÓN / ESTADO / CONDICIÓN
年賀状|ねんがじょう|NENGAJOU|POSTAL DE AÑO NUEVO
欠席|けっせき|KESSEKI|AUSENCIA
出欠|しゅっけつ|SHUKKETSU|ASISTENCIA (O AUSENCIA)
欠点|けってん|KETTEN|UN DEFECTO / PUNTO DÉBIL (= KAKETEIRU TEN)
喜ぶ|よろこぶ|YOROKOBU|ESTAR COMPLACIDO / ALEGRARSE
喜んで|よろこんで|YOROKONDE|CON GUSTO / DE BUENA GANA
政治|せいじ|SEIJI|POLÍTICA
自治会|じちかい|JICHIKAI|ASOCIACIÓN DE VECINOS / ASOCIACIÓN AUTÓNOMA
自治体|じちたい|JICHITAI|ORGANISMO AUTÓNOMO / GOBIERNO LOCAL
治す|なおす|NAOSU|CURAR / SANAR
委員|いいん|IIN|MIEMBRO DEL COMITÉ
委員会|いいんかい|IINKAI|UN COMITÉ
委任状|いにんじょう|ININJOU|UN PODER NOTARIAL / CARTA DE DELEGACIÓN
祝日|しゅくじつ|SHUKUJITSU|UN DÍA FESTIVO / DÍA FERIADO
祝う|いわう|IWAU|CELEBRAR / FELICITAR
お祝い|おいわい|OIWAI|CELEBRACIÓN / FELICITACIÓN
舞台|ぶたい|BUTAI|UN ESCENARIO
舞う|まう|MAU|BAILAR / REVOLOTEAR
お見舞い|おみまい|OMIMAI|VISITA DE CORTESÍA (E.G. A UN ENFERMO)
お礼|おれい|OREI|AGRADECIMIENTO / REGALO DE AGRADECIMIENTO
失礼（な）|しつれい（な）|SHITSUREI|GROSERO / DESCORTÉS
礼儀|れいぎ|REIGI|ETIQUETA / MODALES
多忙（な）|たぼう（な）|TABOU|OCUPADO (CON MUCHAS COSAS)
忙しい|いそがしい|ISOGASHII|OCUPADO
夫妻|ふさい|FUSAI|MARIDO Y MUJER / ESPOSOS
妻|つま|TSUMA|ESPOSA
主張|しゅちょう|SHUCHOU|UNA AFIRMACIÓN / RECLAMO / INSISTENCIA
出張|しゅっちょう|SHUCCHOU|UN VIAJE DE NEGOCIOS
頑張る|がんばる|GANBARU|ESFORZARSE AL MÁXIMO / DAR LO MEJOR DE SÍ
引っ張る|ひっぱる|HIPPARU|TIRAR / JALAR (CON FUERZA)
張る|ハる|HARU|ESTIRAR / TENSAR
奥様|おくさま|OKUSAMA|ESPOSA (FORMA RESPETUOSA)
奥|おく|OKU|PARTE INTERIOR / FONDO
浅い|あさい|ASAI|POCO PROFUNDO / SUPERFICIAL
浅草|あさくさ|ASAKUSA|ASAKUSA (NOMBRE DE LUGAR)
浅ましい|あさましい|ASAMASHII|VERGONZOSO / SÓRDIDO / MISERABLE
～君|くん|KUN|SUFIJO HONORÍFICO PARA HOMBRES JÓVENES O COMPAÑEROS
君|きみ|KIMI|TÚ
永久|えいきゅう|EIKYUU|PERMANENTE / ETERNO
久しぶり|ひさしぶり|HISASHIBURI|MUCHO TIEMPO SIN VERSE
相互|そうご|SOUGO|MUTUO / RECÍPROCO
交互|こうご|KOUGO|ALTERNACIÓN / ALTERNADO
お互いに|おたがいに|OTAGAINI|MUTUAMENTE
追加|ついか|TSUIKA|UNA ADICIÓN / SUPLEMENTO
追う|おう|OU|PERSEGUIR
追い越す|おいこす|OIKOSU|ADELANTAR / REBASAR
追い付く|おいつく|OITSUKU|ALCANZAR / PONERSE AL DÍA
追伸|ついしん|TSUISHIN|POSDATA
伸びる|のびる|NOBIRU|CRECER / ESTIRARSE
伸ばす|のばす|NOBASU|EXTENDER / ESTIRAR
伸びをする|のびをする|NOBIWOSURU|ESTIRARSE (EL CUERPO)
皆|みな|MINA|TODOS
皆さん|みなさん|MINASAN|TODOS USTEDES / TODO EL MUNDO
お歳暮|おせいぼ|OSEIBO|REGALO DE FIN DE AÑO
暮らす|くらす|KURASU|VIVIR / MORAR
暮れ|くれ|KURE|FIN DE AÑO
夕暮れ|ゆうぐれ|YUUGURE|EL ATREDECER / CREPÚSCULO
習慣|しゅうかん|SHUUKAN|UN HABITO / COSTUMBRE
慣れる|なれる|NARERU|ACOSTUMBRARSE A
生活|せいかつ|SEIKATSUI|VIDA / SUSTENTO
活用|かつよう|KATSUYOU|USO PRÁCTICO / UTILIZACIÓN
活字|かつじ|KATSUJI|LETRA DE IMPRENTA / TIPOGRAFÍA
活発（な）|かっぱつ（な）|KAPPATSU|ACTIVO / VIVAZ
恋愛|れんあい|RENAI|AMOR / ROMANCE
恋|こい|KOI|AMOR
恋人|こいびと|KOIBITO|UN AMANTE / NOVIO / NOVIA
恋しい|恋しい|KOISHII|AÑORADO / EXTRAÑADO (SENTIR NOSTALGIA)
健在|けんざい|KENZAI|GOZAR DE BUENA SALUD / ESTAR SANO
健全（な）|けんぜん（な）|KENZEN|SANO / SALUDABLE / INTEGRAL
健やか（な）|すこやか（な）|SUKOYAKA|SANO / SALUDABLE (CUERPO Y MENTE)
健康|けんこう|KENKOU|SALUD
健康保険証|けんこうほけんしょう|KENKOUHOKENSHOU|TARJETA DE SEGURO DE SALUD
祈願|きがん|KIGAN|UNA PLEGARIA / REZO
祈る|いのる|INORU|REZAR / PEDIR UN DESEO
祈り|いのり|INORI|UNA ORACIÓN / REZO
幸福|こうふく|KOUFUKU|FELICIDAD
福祉|ふくし|FUKUSHI|BIENESTAR / BIENESTAR SOCIAL
拝見|はいけん|HAIKEN|VER / MIRAR (FORMA HUMILDE)
拝借|はいしゃく|HAISHAKU|TOMAR PRESTADO (FORMA HUMILDE)
参拝者|さんぱいしゃ|SANPAISHA|VISITANTE (A UN SANTUARIO / TEMPLO)
拝む|おがむ|OGAMU|ADORAR / REZAR CON LAS MANOS JUNTAS
打者|だしゃ|DASHA|UN BATEADOR / GOLPEADOR
打つ|うつ|UTSU|GOLPEAR / PEGAR
打ち合わせ|うちあわせ|UCHIAWASE|REUNIÓN PREVIA / ARREGLO ANTICIPADO
伺う|うかがう|UKAGAU|VISITAR / PREGUNTAR (FORMA HUMILDE)
幸運（な）|こううん（な）|KOUUN|AFORTUNADO / CON SUERTE
不幸（な）|ふこう（な）|FUKOU|INFELIZ / DESFORTUNADO
幸せ（な）|しあわせ（な）|SHIAWASE|FELIZ
幸い|さいわい|SAIWAI|DICHA / FORTUNADAMENTE
失礼（な）|しつれい（な）|SHITSUREI|GROSERO / DESCORTÉS
失業|しつぎょう|SHITSUGYOU|DESEMPLEO
失望|しつぼう|SHITSUBOU|DESESPERACIÓN / DECEPCIÓN
失う|うしなう|USHINAU|PERDER
突然|とつぜん|TOTSUZEN|REPENTINO / DE REPENTE
煙突|えんとつ|ENTOTSU|UNA CHIMENEA
突き当たり|つきあたり|TSUKIATARI|EL FINAL (E.G. DE LA CALLE / PASILLO)
突っ込む|つっこむ|TSUKKOMU|METER EN / EMANDARSE EN / ENCHUFAR
全然|ぜんぜん|ZENZEN|PARA NADA / EN ABSOLUTO (CON NEGATIVO)
自然|しぜん|SHIZEN|NATURALEZA / NATURAL
当然|とうぜん|TOUZEN|POR SUPUESTO / NATURALMENTE
天然|てんねん|TENNEN|NATURAL / NO ARTIFICIAL
諸～|しょ～|SHO|VARIOS / DIVERSOS
諸問題|しょもんだい|SHOMONDAI|VARIOS PROBLEMAS
諸般|しょはん|SHOHAN|VARIEDAD / DE TODO TIPO
事情|じじょう|JIJOU|CIRCUNSTANCIA / SITUACIÓN
友情|ゆうじょう|YUUJOU|UNA AMISTAD
表情|ひょうじょう|HYOUJOU|EXPRESIÓN FACIAL
情け|なさけ|NASAKE|SIMPATÍA / COMPASIÓN / MISERICORDIA
情けない|なさけない|NASAKENAI|LAMENTABLE / VERGONZOSO / DEPLORABLE
引退|いんたい|INTAI|RETIRO / JUBILACIÓN (E.G. DEPORTE, POLÍTICA)
退院|たいいん|TAIIN|ALTA HOSPITALARIA / SALIR DEL HOSPITAL
退学|たいがく|TAIGAKU|ABANDONO ESCOLAR / RETIRO DE LA ESCUELA
退く|しりぞく|SHIRIZOKU|RETIRARSE / RETROCEDER
職業|しょくぎょう|SHOKUGYOU|UNA OCUPACIÓN / PROFESIÓN
職場|しょくば|SHOKUBA|UN LUGAR DE TRABAJO
退職|たいしょく|TAISHOKU|RETIRO / JUBILACIÓN (DEL TRABAJO)
職人|しょくにん|SHOKUNIN|UN ARTESANO
紹介|しょうかい|SHOUKAI|INTRODUCCIÓN / PRESENTACIÓN
介入|かいにゅう|KAINYUU|INTERVENCIÓN
介護|かいご|KAIGO|CUIDADOS DE ENFERMERÍA / ASISTENCIA
一次試験|いちじしけん|ICHIJI SHIKEN|EL PRIMER EXAMEN
次|つぎ|TSUGI|EL SIGUIENTE
次第|しだい|SHIDAI|(1) TAN PRONTO COMO / (2) DEPENDIENDO DE
文章|ぶんしょう|BUNSHOU|UN TEXTO / ENSAYO / COMPOSICIÓN
章|しょう|SHOU|UN CAPÍTULO
対する|たいする|TAISURU|HACIA / CONTRA
反対|はんたい|HANTAI|OPOSICIÓN / LO CONTRARIO
～対～|たい|TAI|VERSUS / CONTRA
対照的（な）|たいしょうてき（な）|TAISHOUTEKI|CONTRASTANTE
対|つい|TSUI|UN PAR / PAREJA
最初|さいしょ|SAISHO|EL PRINCIPIO / AL PRINCIPIO
最後|さいご|SAIGO|EL FINAL / ÚLTIMO
最近|さいきん|SAIKIN|RECIENTEMENTE / ÚLTIMAMENTE
最も|もっとも|MOTTOMO|EL MÁS / MÁXIMO
適当（な）|てきとう（な）|TEKITOU|ADECUADO / APROPIADO
適切（な）|てきせつ（な）|TEKISETSU|APROPIADO / OPORTUNO
適する|てきする|TEKISURU|SER ADECUADO PARA / ADAPTARSE A
適度（な）|てきど（な）|TEKIDO|MODERADO / EN SU JUSTA MEDIDA
誤解|ごかい|GOKAI|MALENTENDIDO
誤り|あやまり|AYAMARI|UN ERROR / EQUIVOCACIÓN
直線|ちょくせん|CHOKUSEN|UNA LÍNEA RECTA
正直（な）|しょうじき（な）|SHOUJIKI|HONESTO
直す|なおす|NAOSU|ARREGLAR / REPARAR / CORREGIR
素直（な）|すなお（な）|SUNAO|OBEDIENTE / SUMISO / DOCIL
直ちに|ただちに|TADACHINI|INMEDIATAMENTE
例|れい|REI|UN EJEMPLO
例外|れいがい|REIGAI|UNA EXCEPCIÓN
実例|じつれい|JITSUREI|UN EJEMPLO REAL / INSTANCIA
例えば|たとえば|TATOEBA|POR EJEMPLO
例える|たとえる|TATOERU|COMPARAR / ASIMILAR
名詞|めいし|MEISHI|UN SUSTANTIVO
動詞|どうし|DOUSHI|UN VERBO
自動詞|じどうし|JIDOUSHI|UN VERBO INTRANSITIVO
他動詞|たどうし|TADOUSHI|UN VERBO TRANSITIVO
形式|けいしき|KEISHIKI|FORMA / FORMALIDAD
形容詞|けいようし|KEIYOUSHI|UN ADJETIVO
図形|ずけい|ZUKEI|UN DIAGRAMA / FIGURA GEOMÉTRICA
人形|にんぎょう|NINGYOU|UNA MUÑECA / MARIONETA
形|かたち|KATACHI|FORMA / FIGURA
救助|きゅうじょ|KYUUJO|RESCATE / AUXILIO
助詞|じょし|JOSHI|UNA PARTÍCULA (GRAMATICAL)
助手|じょしゅ|JOSHU|UN ASISTENTE
助かる|たすかる|TASUKARU|SALVARSE / SER DE AYUDA
助ける|たすける|TASUKERU|AYUDAR / SALVAR
副詞|ふくし|FUKUSHI|UN ADVERBIO
副～|ふく～|FUKU|VICE～ / ASISTENTE
周囲|しゅうい|SHUUI|PERÍMETRO / ALREDEDORES
囲む|かこむ|KAKOMU|RODEAR
夢中|むちゅう|MUCHUU|ESTAR ENMUTADO / ABSORBIDO / ENFOCADO
夢|ゆめ|YUME|UN SUEÑO
専門|せんもん|SENMON|ESPECIALIDAD
専用|せんよう|SENYOU|USO EXCLUSIVO
専攻|せんこう|SENKOU|UN ESTUDIO PRINCIPAL / ESPECIALIZACIÓN MAESTRÍA
歴史|れきし|REKISHI|HISTORIA
～史|し|SHI|HISTORIA DE ~
区域|くいき|KUIKI|UN ÁREA / ZONA
地域|ちいき|CHIIKI|UN ÁREA / REGIÓN
祭日|さいじつ|SAIJITSU|UN DÍA FESTIVO / DÍA DE FESTIVAL
～祭|さい|SAI|FESTIVAL DE ~
（お）祭り|まつり|MATSURI|FESTIVAL
検査|けんさ|KENSA|UNA INSPECCIÓN / PRUEBA
調査|ちょうさ|CHOUSA|UNA INVESTIGACIÓN / INDAGACIÓN
審査|しんさ|SHINSA|EXAMEN / EVALUACIÓN / JURADO
～戦|せん|SEN|UNA BATALLA / COMBATE / TORNEO DE ~
大戦|たいせん|TAISEN|UNA GRAN GUERRA (E.G. PRIMERA GUERRA MUNDIAL)
戦争|せんそう|SENSOU|GUERRA
戦う|たたかう|TATAKAU|PELEAR / LUCHAR
競争|きょうそう|KYOUSOU|COMPETENCIA
争う|あらそう|ARASOU|PELEAR / DISPUTAR
将来|しょうらい|SHOURAI|FUTURO
将棋|しょうぎ|SHOUGI|SHOGI (AJEDREZ JAPONÉS)
歩道橋|ほどうきょう|HODOUKYOU|UN PUENTE PEATONAL
鉄橋|てっきょう|TEKKYOU|UN PUENTE FERROVIARIO
橋|はし|HASHI|UN PUENTE
架け橋|かけはし|KAKEHASHI|UN PUENTE / ENLACE / INTERMEDIARIO
憎い|にくい|NIKUI|DETESTABLE / ABORRECIBLE
憎む|にくむ|NIKUMU|DETESTAR / ODIAR
憎しみ|にくしみ|NIKUSHIMI|ODIO / ENEMISTAD
憎らしい|にくらしい|NIKURASHII|DETESTABLE / ODIORE
自殺|じさつ|JISATSU|UN SUICIDIO
殺す|ころす|KOROSU|MATAR
悲観|ひかん|HIKAN|PESIMISMO
悲しむ|かなしむ|KANASHIMU|DEPLORAR / LAMENTAR / SENTIR TRISTEZA
悲しい|かなしい|KANASHII|TRISTE
恥|はじ|HAJI|VERGÜENZA / HUMILLACIÓN
恥ずかしい|はずかしい|HAZUKASHII|ESTAR AVERGONZADO
感じる|かんじる|KANJIRU|SENTIR
感情|かんじょう|KANJOU|EMOCIÓN / SENTIMIENTO
感動|かんどう|KANDOU|EMOCIÓN / INSPIRACIÓN / CONMOCIÓN
感心（な）|かんしん（な）|KANSHIN|ADMIRABLE
地球|ちきゅう|CHIKYUU|LA TIERRA (PLANETA)
電球|でんきゅう|DENKYUU|UNA BOMBILLA / FOCO
野球|やきゅう|YAKYUU|BÉISBOL
球|たま|TAMA|UNA BOLA / ESFERA
平和|へいわ|HEIWA|PAZ
和式|わしき|WASHIKI|ESTILO JAPONÉS
愛|あい|AI|AMOR
愛する|あいする|AISURU|AMAR
愛情|あいじょう|AIJOU|AMOR / AFECTO
恋愛|れんあい|RENAI|AMOR / ROMANCE
仲|なか|NAKA|RELACIONES / VÍNCULO / TÉRMINOS
仲間|なかま|NAKAMA|UN AMIGO / CÍRCULO de AMIGOS / COMPAÑERO
改良|かいりょう|KAIRYOU|MEJORA / REFORMA
良い|よい|YOI|BUENO


// --- Frases del repertorio del Jefe (Se elegirán 2 al azar cada 1000 puntos) ---
//BOSS_FRAS|frase japonesa|Frase en Romaji|Traducción al español
BOSS_FRAS|自分の望み通りの大学に入学できた。|JIBUNNONOZOMIDOORINODAIGAKUNINYUUGAKUDEKITA|PUDO INGRESAR A LA UNIVERSIDAD EXACTAMENTE COMO LO DESEABA.
BOSS_FRAS|来日する友人を空港の到着ロビーで待つ。|RAINICHISURUYUUJINWOKUUKOUNOTOUCHAKUROBIIDEMATSU|ESPERO EN EL VESTÍBULO DE LLEGADAS DEL AEROPUERTO A UN AMIGO QUE VIENE A JAPÓN.
BOSS_FRAS|商品の配送を依頼する。|SHOUHINNOHAISOUWOIRAISURU|SOLICITAR EL ENVÍO DE UN PRODUCTO.
BOSS_FRAS|市民が駅前に立ち署名を集める活動を始めた。|SHIMINGAEKIMAENITACHISHOMEIWOATSUMERUKAT SUDOUWOHAJIMETA|LOS CIUDADANOS SE PUSIERON DE PIE FRENTE A LA ESTACIÓN Y COMENZARON UNA CAMPAÑA PARA RECOGER FIRMAS.
BOSS_FRAS|日本では結婚すると夫の姓になる女の人が多い。|NIHONDEHAKEKKONSURUTOOTTONOSEININARUONNANOHITOGAOOI|EN JAPÓN, HAY MUCHAS MUJERES QUE ADOPTAN EL APELLIDO DEL ESPOSO CUANDO SE CASAN.
BOSS_FRAS|朝夕の通勤ラッシュ時は電車が満員になる。|ASAYUUNOTSUUKINRASSHUJIHADENSHAGAMAN'INNARU|DURANTE LA HORA PUNTA DE LA MAÑANA Y DE LA TARDE, LOS TRENES SE LLENAN POR COMPLETO.
BOSS_FRAS|お客様に迷子のお知らせを申し上げます。|OKYAKUSAMANIMAIGONOOSHIRASEWOMOUSHIAGEMASU|LES PRESENTAMOS A NUESTROS CLIENTES UN ANUNCIO SOBRE UN NIÑO PERDIDO.
BOSS_FRAS|パスポートの申請をする。|PASUPOOTONOSHINSEIWOSURU|SOLICITAR UN PASAPORTE.
BOSS_FRAS|ゴミの出し方は地方自治体によって違う。|GOMINODASHIKATAHACHIHOUJICHITAINIYOTTECHIGAU|LA FORMA DE SACAR LA BASURA VARÍA SEGÚN EL MUNICIPIO LOCAL.
BOSS_FRAS|短所、つまり欠点はだれにでもあるだろう。|TANSHOTSUMARIKETTENHADARENIDEMOARUDAROU|TODOS TIENEN PUNTOS DÉBILES, ES DECIR, DEFECTOS.
BOSS_FRAS|再婚というのはもう一度結婚することです。|SAIKONTOIUNOHAMOUICHIDOKEKKONSURUKOTODESU|EL SEGUNDO MATRIMONIO SIGNIFICA CASARSE UNA VEZ MÁS.
BOSS_FRAS|結婚式の招待状に返事を書く。|KEKKONSHIKINOSHOUTAIJOUNIHENJIWOKAKU|ESCRIBIR UNA RESPUESTA A UNA INVITACIÓN DE BODA.
BOSS_FRAS|梅雨明けの暑い時に、日本では暑中見舞いを出す。|TSUYUAKENOATSUITOKININIHONDEHASHOCHUUMIMAIWODASU|EN JAPÓN, SE ENVÍAN TARJETAS DE SALUDO DE VERANO DURANTE LOS DÍAS CALUROSOS POSTERIORES A LA TEMPORADA DE LLUVIAS.
BOSS_FRAS|5月5日は「こどもの日」、祝日です。|GOGATSUITSUKAHAKODOMONOHISHUKUJITSUDESU|EL 5 DE MAYO ES EL "DÍA DEL NIÑO", UN DÍA FESTIVO.
BOSS_FRAS|明日は北海道へ出張だ。|ASHITAHAHOKKAIDOUHESHUTCHOUDA|MAÑANA TENGO UN VIAJE DE NEGOCIOS A HOKKAIDO.
BOSS_FRAS|りんごを送ってもらったのでお礼の手紙を出す。|RINGOWOOKUTTEMORATTANODEOREINOTEGAMIWODASU|ENVÍO UNA CARTA DE AGRADECIMIENTO PORQUE ME ENVIARON MANZANAS.
BOSS_FRAS|手紙を出す。|TEGAMIWODASU|ENVIAR UNA CARTA.
BOSS_FRAS|久しぶりに会った友達はひげを伸ばしていた。|HISASHIBURINIATTATOMODACHIHAHIGEWONOBASHITEITA|EL AMIGO QUE CONOCÍ DESPUÉS DE MUCHO TIEMPO SE HABÍA DEJADO CRECER LA BARBA.
BOSS_FRAS|この道路は追い越し禁止です。|KONODOUROHAOIKOSHIKINSHIDESU|ESTÁ PROHIBIDO ADELANTAR EN ESTA CARRETERA.
BOSS_FRAS|この川は浅いので、子どもたちが遊ぶのにちょうどいい。|KONOKAWAHAASAINODEKODOMOTACHIGAASOBUNONICHOUDOII|ESTE RÍO ES POCO PROFUNDO, POR LO QUE ES IDEAL PARA QUE LOS NIÑOS JUEGUEN.
BOSS_FRAS|P.S. というのは追伸のことです。|PSTOIUNOHATSUISHINNOKOTODESU|P.S. SIGNIFICA POSDATA.
BOSS_FRAS|年の暮れにお世話になった人にお礼をする習慣がある。|TOSHINOKURENIOSEWANINATTACITONIOREIWOSURUSHUUKANGAARU|EXISTE LA COSTUMBRE DE DAR UN AGRADECIMIENTO AL FINAL DEL AÑO A LAS PERSONAS QUE NOS AYUDARON.
BOSS_FRAS|健康保険証を持ってきてください。|KENKOUHOKENSHOWOMOTTEKITEKUDASAI|POR FAVOR, TRAIGA SU TARJETA DE SEGURO DE SALUD.
BOSS_FRAS|私はいつも食事の前にお祈りをします。|WATASHIHAITSUMOSHOKUJINOMAENIOINORIWOSHIMASU|SIEMPRE HAGO UNA ORACIÓN ANTES DE LAS COMIDAS.
BOSS_FRAS|活発な議論をする。|KAPPATSUNAGIRONWOSURU|LLEVAR A CABO UNA DISCUSIÓN ENÉRGICA.
BOSS_FRAS|「ちょっとお伺いしますが、郵便局はどちらでしょうか。」|CHOTTOOUKAGAISHIMASUGAYUUBINKYOKUHADOCHIRADESHOUKA|“DISCULPE, QUERÍA PREGUNTARLE, ¿DÓNDE QUEDA LA OFICINA DE CORREOS?”
BOSS_FRAS|「君には失望したよ」と部長に言われてしまった。|KIMINIHASHITSUBOSHITAYOTOBUCHOUNIIWARETESHIMATTA|EL JEFE DE DEPARTAMENTO ME DIJO: “ESTOY DECEPCIONADO DE TI”.
BOSS_FRAS|「ご結婚おめでとう！ お幸せに！」|GOKEKKONOMEDETOUOSHIAWASENI|“¡FELICIDADES POR TU MATRIMONIO! ¡QUE SEAN MUY FELICES!”
BOSS_FRAS|雪のため、元日の参拝者はやや少なかった。|YUKINOTAMEGANJITSUNOSANPAISHAHAYAYASUKUNAKATTA|DEBIDO A LA NIEVE, LOS VISITANTES AL SANTUARIO EL DÍA DE AÑO NUEVO FUERON UN POCO MENOS DE LO HABITUAL.
BOSS_FRAS|この辺りも開発が進み、自然が失われつつある。|KONOATARIMOKAIHATSUGASUMISHIZENGAUSHINAWARETSUTSUARU|EL DESARROLLO TAMBIÉN AVANZA EN ESTA ZONA, Y LA NATURALEZA SE ESTÁ PERDIENDO POCO A POCO.
BOSS_FRAS|今の職場は友人に紹介してもらった。|IMANOSHOKUBAHAYUUJINNISHOUKAISHITEMORATTA|MI LUGAR DE TRABAJO ACTUAL ME LO PRESENTÓ UN AMIGO.
BOSS_FRAS|「まっすぐ行って、突き当たりを右に曲がってください。」|MASSUGUITTETSUKIATARIWOMIGINIMAGATTEKUDASAI|“VAYA RECTO Y, AL FINAL DE LA CALLE, GIRE A LA DERECHA.”
BOSS_FRAS|職業訓練を受けて仕事を見つける。|SHOKUGYOUKUNRENWOUKETESHIGOTOWOMITSUKERU|RECIBIR FORMACIÓN PROFESIONAL Y ENCONTRAR UN TRABAJO.
BOSS_FRAS|その小説の最初の章を読み終えたところです。|SONOSHOUSETSUNOSAISHONOSHOUWOYOMIOETATOKORODESU|ACABO DE TERMINAR DE LEER EL PRIMER CAPÍTULO DE ESA NOVELA.
BOSS_FRAS|健康のために適度な運動をするようにしています。|KENKOUNOTAMENITEKIDONAUNDOUWOSURUYOUNISHITEIMASU|ME ASEGURO DE HACER EJERCICIO MODERADO POR EL BIEN DE MI SALUD.
BOSS_FRAS|明日行くかどうかは天気次第です。|ASHITAIKUKADOCHIRAHATENKISHIDAIDESU|EL HECHO DE IR O NO MAÑANA DEPENDE DEL CLIMA.
BOSS_FRAS|直ちに安全な場所に移動してください。|TADACHINIANZENNABASHOUNIIDOUHITEKUDASAI|POR FAVOR, TRASLÁDESE INMEDIATAMENTE A UN LUGAR SEGURO.
BOSS_FRAS|周囲の住民はマンションの建設に反対している。|SHUUINOJUUMINHAMANSHONNOKENSETSUNIHANTAISHITEIRU|LOS RESIDENTES DE LOS ALREDEDORES SE OPONEN A LA CONSTRUCCIÓN DEL CONDOMINIO.
BOSS_FRAS|形式も重要だが、内容はもっと重要だ。|KEISHIKIMOJUUYOUDAGANAIYOUHAMOTTOJUUYOUDA|EL FORMATO TAMBIÉN ES IMPORTANTE, PERO EL CONTENIDO LO ES AÚN MÁS.
BOSS_FRAS|副社長がよく働いてくれるので、社長は助かっている。|FUKUSHACHOUGAYOKUHATARAITEKURERUNODESHACHOUHATASUKATTEIRU|COMO EL VICEPRESIDENTE TRABAJA MUY BIEN, EL PRESIDENTE SE SIENTE MUY ALIVIADO (AYUDADO).
BOSS_FRAS|彼女は花に例えると白いユリです。|KANOJOHAHANANITATOERUTOSHIROIYURIDESU|SI LA COMPARAMOS CON UNA FLOR, ELLA ES UN LIRIO BLANCO.
BOSS_FRAS|弟は野球に夢中で、将来はプロの選手になりたいと言っている。|OTOUTOHAYAKYUUNIMUCHUUDESHOURAIHAPURONOSENSHUNINARITAITOITTEIRU|MI HERMANO MENOR ESTÁ OBSESIONADO CON EL BÉISBOL Y DICE QUE QUIERE SER JUGADOR PROFESIONAL EN EL FUTURO.
BOSS_FRAS|大学では数学を専攻した。|DAIGAKUDEHASUUGAKUWOSENKOUSHITA|ME ESPECIALICÉ EN MATEMÁTICAS EN LA UNIVERSIDAD.
BOSS_FRAS|この建物のトイレは洋式と和式のほかに車いす用のものもある。|KONOTATEMONONOTOIREHAYOUSHIKITOWASHIKINOHOKANIKURUMAISUYOUNOMONOMOARU|LOS BAÑOS DE ESTE EDIFICIO CUENTAN CON ESTILO OCCIDENTAL Y ESTILO JAPONÉS, ADEMÁS DE UNO PARA SILLAS DE RUEDAS.
BOSS_FRAS|あの人と私はオリンピックで金メダルを争った仲だ。|ANOHITOTOWATASHIHAORINPIKKUDEKINMEDARUWOARASOTTANAKADA|ESA PERSONA Y YO SOMOS COMPAÑEROS QUE DISPUTARON UNA MEDALLA DE ORO EN LOS JUEGOS OLÍMPICOS.
BOSS_FRAS|この製品は改良を重ね、良い味になった。|KONOSEIHINHAKAIRYOUWOKASANEIIAJININATTA|ESTE PRODUCTO HA MEJORADO REPETIDAMENTE Y HA ALCANZADO UN BUEN SABOR.
BOSS_FRAS|姉から愛情のこもった手紙をもらった。|ANEKARAAIJOUNOKOMOTTATEGAMIWOMORATTA|RECIBÍ UNA CARTA LLENA DE AFECTO DE PARTE DE MI HERMANA MAYOR.
BOSS_FRAS|試験に出される問題の傾向を調べて受験勉強をする。|SHIKENNIDASARERUMONDAINOKEIKOWOSHIRABETEJUKENBENKYOUWOSURU|ESTUDIAR PARA EL EXAMEN INVESTIGANDO LA TENDENCIA DE LAS PREGUNTAS QUE SE PRESENTAN.
BOSS_FRAS|「恐れ入りますが、荷物はそちらに置いてください。」|OSOREIRIMASUGANIMOTSUHASOCHIRANIOITEKUDASAI|“DISCULPE LA MOLESTIA, PERO POR FAVOR COLOQUE EL EQUIPAJE ALLÍ.”
BOSS_FRAS|アフリカ原産のお茶を飲む。|AFURIKAGENSANNOOCHAWONOMU|BEBER TÉ ORIGINARIO DE ÁFRICA.
BOSS_FRAS|この車には ABS という安全装置がついています。|KONOKURUMANIHAABSTOIUANZENSOUCHIGATSUITEIMASU|ESTE AUTOMÓVIL ESTÁ EQUIPADO CON UN DISPOSITIVO DE SEGURIDAD LLAMADO ABS.
`.trim();
