export const KANJI_SEMANA_7_RAW = `
課|か|KA|LECCIÓN / SECCIÓN
課長|かちょう|KACHOU|JEFE DE SECCIÓN
日課|にっか|NIKKA|TAREA DIARIA / LECCIÓN DIARIA
課程|かてい|KATEI|CURSO / PLAN DE ESTUDIOS
過程|かてい|KATEI|PROCESO / CURSO
程度|ていど|TEIDO|GRADO / CANTIDAD
日程|にってい|NITTEI|HORARIO / PROGRAMACIÓN
制度|せいど|SEIDO|SISTEMA
制限|せいげん|SEIGEN|RESTRICCIÓN / LIMITACIÓN
制作|せいさく|SEISAKU|TRABAJO / PRODUCCIÓN
体制|たいせい|TAISEI|SISTEMA / ESTRUCTURA
講座|こうざ|KOUZA|CLASE / CURSO
講義|こうぎ|KOUGI|CONFERENCIA / LECCIÓN ACADÉMICA
講演|こうえん|KOUEN|CONFERENCIA / DISCURSO
講師|こうし|KOUSHI|CONFERENCIANTE / PROFESOR
初級|しょきゅう|SHOKYUU|NIVEL PRINCIPIANTE
中級|ちゅうきゅう|CHUUKYUU|NIVEL INTERMEDIO
上級|じょうきゅう|JOUKYUU|NIVEL AVANZADO
高級|こうきゅう|KOUKYUU|CLASE ALTA / ALTO RANGO
基本|きほん|KIHON|BASE / FUNDAMENTOS
基礎|きそ|KISO|FUNDACIÓN / BASE / TRABAJO PREPARATORIO
基準|きじゅん|KIJUN|ESTÁNDAR / CRITERIO
基地|きち|KICHI|BASE (MILITAR, DE OPERACIONES, ETC.)
指導|しどう|SHIDOU|LIDERAZGO / GUÍA
導入|どうにゅう|DOUNYUU|INTRODUCCIÓN
導く|みちびく|MICHIBIKU|GUIAR / CONDUCIR
求人|きゅうじん|KYUUJIN|OFERTA DE EMPLEO / SE BUSCA PERSONAL
要求|ようきゅう|YOUKYUU|DEMANDA / REQUISITO
請求書|せいきゅうしょ|SEIKYUUSHO|FACTURA / CUENTA
求める|もとめる|MOTOMERU|PEDIR / DEMANDAR / REQUERIR
簡単|かんたん|KANTAN|FÁCIL / SIMPLE
単語|たんご|TANGO|PALABRA / VOCABLO
単位|たんい|TANI|UNIDAD / CRÉDITO ACADÉMICO
単に|たんに|TANNI|MERAMENTE / SIMPLEMENTE
単なる|たんなる|TANNARU|MERO / SIMPLE
許可|きょか|KYOKA|PERMISO / AUTORIZACIÓN
免許|めんきょ|MENKYO|PERMISO / LICENCIA
許す|ゆるす|YURUSU|PERMITIR / PERDONAR
給料|きゅうりょう|KYUURYOU|SALARIO / SUELDO
支給|しきゅう|SHIKYUU|PAGO / ABONO
供給|きょうきゅう|KYOUKYUU|SUMINISTRO / PROVISIÓN
月給|げっきゅう|GEKKYUU|SALARIO MENSUAL
週給|しゅうきゅう|SHUUKYUU|SALARIO SEMANAL
日給|にっきゅう|NIKKYUU|SALARIO DIARIO
給与|きゅうよ|KYUUYO|SUBSIDIO / ASIGNACIÓN / PAGA
を与える|あたえる|ATAERU|DAR / PRESENTAR / OTORGAR
応募|おうぼ|OUBO|SOLICITUD / POSTULACIÓN
応じる|おうじる|OUJIRU|RESPONDER / CONTESTAR
一応|いちおう|ICHIOU|PROVISIONALMENTE / POR EL MOMENTO
応用|おうよう|OUYOU|APLICACIÓN PRÁCTICA
校庭|こうてい|KOUTEI|PATIO COLEGIAL / PATIO DE RECREO
家庭|かてい|KATEI|HOGAR / FAMILIA
庭|にわ|NIWA|JARDÍN
教育|きょういく|KYOUIKU|EDUCACIÓN
体育|たいいく|TAIIKU|EDUCACIÓN FÍSICA
育児|いくじ|IKUJI|CUIDADO INFANTIL / CRIANZA
育つ|そだつ|SODATU|CRECER / DESARROLLARSE
育てる|そだてる|SODATERU|CRIAR / EDUCAR / LEVANTAR
猫|ねこ|NEKO|GATO
探検|たんけん|TANKEN|EXPLORACIÓN / EXPEDICIÓN
探す|さがす|SAGASU|BUSCAR
探る|さぐる|SAGURU|SONDEAR / INVESTIGAR / EXPLORAR
灰|はい|HAI|CENIZA
灰色|hいいろ|HAIIRO|COLOR GRIS
灰皿|はいざら|HAIZARA|CENICERO
車輪|しゃりん|SHARIN|RUEDA (DE COCHE)
指輪|ゆびわ|YUBIWA|ANILLO
首輪|くびわ|KUBIWA|COLLAR (PARA ANIMALES)
今晩|こんばん|KONBAN|ESTA NOCHE
晩御飯|ばんごはん|BANGOHAN|CENA
毎晩|まいばん|MAIBAN|TODAS LAS NOCHES
劇|げき|GEKI|DRAMA / OBRA DE TEATRO
劇団|げきだん|GEKIDAN|COMPAÑÍA TEATRAL
劇場|げきじょう|GEKIJOU|TEATRO / SALA DE TEATRO
演劇|えんげき|ENGEKI|OBRA TEATRAL / TEATRO
公園|こうえん|KOUEN|PARQUE
公演|こうえん|KOUEN|ACTUACIÓN PÚBLICA / REPRESENTACIÓN
公共|こうきょう|KOUKYOU|PÚBLICO / COMUNAL
公務員|こうむいん|KOUMUIN|FUNCIONARIO PÚBLICO
日本舞踊|にほんぶよう|NIHONBUYOU|DANZA TRADICIONAL JAPONESA
踊る|おどる|ODORU|BAILAR
踊り|おどり|ODORI|DANZA / BAILE
種類|しゅるい|SHURUI|TIPO / CLASE / ESPECIE
人種|じんしゅ|JINSHU|RAZA (HUMANA)
雑種|ざっしゅ|ZASSHU|HÍBRIDO / RAZA MIXTA
種|たね|TANE|SEMILLA
匹敵する|ひってきする|HITTEKISURU|RIVALIZAR / COMPARARSE CON
～匹|ひき|HIKI|CONTADOR PARA ANIMALES PEQUEÑOS
渡米|とべい|TOBEI|IR A ESTADOS UNIDOS
渡る|わたる|WATARU|CRUZAR / ATRAVESAR
渡す|わたす|WATASU|ENTREGAR / PASAR AL OTRO LADO
渡辺|わたなべ|WATANABE|WATANABE (APELLIDO)
乗馬|じょうば|JOUBA|EQUITACIÓN / MONTAR A CABALLO
馬|うま|UMA|CABALLO
貝|かい|KAI|CONCHA / MARISCO
貝がら|かいがら|KAIGARA|CONCHA (VACÍA)
～酒|しゅ|SHU|ALCOHOL / LICOR (SUFIJO)
酒|さけ|SAKE|ALCOHOL / LICOR / SAKE
酒屋|さかや|SAKAYA|TIENDA DE LICORES
居酒屋|いざかや|IZAKAYA|TABERNA JAPONESA / PUB
蒸発|じょうはつ|JOUHATSU|EVAPORACIÓN
水蒸気|すいじょうき|SUIJOUKI|VAPOR DE AGUA
蒸す|むす|MUSU|COCINAR AL VAPOR
蒸し暑い|むしあつい|MUSHIATSUI|BOCHORNOSO / HÚMEDO Y CALUROSA
干す|ほす|HOSU|COLGAR PARA SECAR / SECAR
干物|ひもの|HIMONO|COMIDA SECA (PESCADO, ETC.)
竹|たけ|TAKE|BAMBÚ
竹の子|たけのこ|TAKENOKO|BROTE DE BAMBÚ
卵黄|らんおう|RANOU|YEMA DE HUEVO
卵|たまご|TAMAGO|HUEVO
大根|だいこん|DAIKON|RÁBANO BLANCO JAPONÉS
根|ね|NE|RAÍZ
屋根|やね|YANE|TEJADO / TECHO
材料|ざいりょう|ZAIRYOU|INGREDIENTES / MATERIALES
原材料|げんざいりょう|GENZAIRYOU|MATERIAS PRIMAS
材質|ざいしつ|ZAISHITSU|PROPIEDADES DEL MATERIAL / CALIDAD
教材|きょうざい|KYOUZAI|MATERIALES DIDÁCTICOS
植物|しょくぶつ|SHOKUBUTSU|PLANTA / VEGETACIÓN
植える|うえる|UERU|PLANTAR / CULTIVAR
植木|うえき|UEKI|PLANTAS EN MACETA / ARBUSTO DE JARDÍN
田植え|たうえ|TAUE|PLANTACIÓN DE ARROZ
砂糖|さとう|SATOU|AZÚCAR
砂漠|さばく|SABAKU|DESIERTO
砂|すな|SUNA|ARENA
牛乳|ぎゅうにゅう|GYUUNYUU|LECHE (DE VACA)
乳製品|にゅうせいひん|NYUUSEIHIN|PRODUCTOS LÁCTEOS
乳児|にゅうじ|NYUUJI|BEBÉ (MENOR DE UN AÑO)
乳|ちち|CHICHI|LECHE / SENOS
含む|ふくむ|FUKUMU|ESTAR INCLUIDO / CONTENER
含める|ふくめる|FUKUMERU|INCLUIR
炭水化物|たんすいかぶつ|TANSUIKABUTSU|CARBOHIDRATO
石炭|せきたん|SEKITAN|CARBÓN (MINERAL)
炭|すみ|SUMI|CARBÓN VEGETAL
脂肪|しぼう|SHIBOU|GRASA
脂質|ししつ|SHISHITSU|LÍPIDOS / GRASAS
油脂|ゆし|YUSHI|ACEITES Y GRASAS
脂|あぶら|ABURA|GRASA / MANTECA
封筒|ふうとう|FUUTOU|UN SOBRE
水筒|すいとう|SUITOU|UNA CANTIMPLORA / BOTELLA DE AGUA
筒|つつ|TSUTSU|UN TUBO / TUBERÍA
卒業|そつぎょう|SOTSUGYOU|GRADUACIÓN
卒業証明書|そつぎょうしょうめいしょ|SOTSUGYOUSHOUMEISHO|UN DIPLOMA
成績|せいせき|SEISEKI|RESULTADOS / EXPEDIENTE
業績|ぎょうせき|GYOUSEKI|LOGRO / RESULTADOS COMERCIALES
実績|じっせき|JISSEKI|RESULTADOS REALES / LOGRO
論文|ろんぶん|RONBUN|UNA TESIS / TRATADO
議論|ぎろん|GIRON|UN ARGUMENTO / DISCUSIÓN / DEBATE
結論|けつろん|KETSURON|UNA CONCLUSIÓN
論じる|ろんじる|RONJIRU|ARGUMENTAR / DISCUTIR / DEBATIR
志望|しぼう|SHIBOU|DESEO / ANHELO
意志|いし|ISHI|VOLUNTAD / INTENCIÓN
記述|きじゅつ|KIJUTSU|UNA DESCRIPCIÓN
口述|こうじゅつ|KOUJUTSU|DECLARACIÓN VERBAL
前述|ぜんじゅつ|ZENJUTSU|LO ANTERIORMENTE MENCIONADO / LO CITADO ARRIBA
述べる|のべる|NOBERU|DECLARAR / MENCIONAR
結構|けっこう|KEKKOU|ESPLÉNDIDO / AGRADABLE / BIEN
構成|こうせい|KOUSEI|COMPOSICIÓN
構内|こうない|KOUNAI|UN CAMPUS / RECINTO / PREDIOS
構う|かまう|KAMAU|IMPORTAR / PREOCUPARSE POR
遅刻|ちこく|CHIKOKU|RETRASO / TARDANZA
遅い|おそい|OSOI|LENTO
遅れる|おくれる|OKURERU|LLEGAR TARDE / RETRASARSE
仮名|かな|KANA|SILABARIO JAPONÉS
振り仮名|ふりがな|FURIGANA|CARACTERES KANA ESCRITOS AL LADO DE LOS KANJIS
仮定|かてい|KATEI|SUPOSICIÓN / HIPÓTESIS
仮|かり|KARI|TEMPORAL / PROVISIONAL
机|つくえ|TSUKUE|UN ESCRITORIO
～冊|さつ|SATSU|CONTADOR PARA LIBROS
冊子|さっし|SASSHI|UN FOLLETO / CUADERNILLO
採点|さいてん|SAITEN|CALIFICACIÓN / PUNTUACIÓN
採用|さいよう|SAIYOU|ADOPCIÓN / EMPLEO / CONTRATACIÓN
採集|さいしゅう|SAISHUU|RECOLECCIÓN / RECOPILACIÓN
採る|とる|TORU|ADOPTAR (UNA MEDIDA / PROPUESTA)
濃度|のうど|NOUDO|CONCENTRACIÓN / DENSIDAD
濃い|こい|KOI|CONCENTRADO / OSCURO (COLOR)
鉛筆|えんぴつ|ENPITSU|UN LÁPIZ
筆者|ひっしゃ|HISSHA|UN ESCRITOR / AUTOR
筆記|ひっき|HIKKI|TOMAR NOTAS / COPIAR / ESCRITO
筆|ふで|FUDE|UN PINCEL PARA ESCRIBIR
航空|こうくう|KOUKUU|AVIACIÓN / VUELO
運航|うんこう|UNKOU|OPERACIÓN (DE BARCOS, AVIONES, ETC.)
欠航|けっこう|KEKKOU|SUSPENSIÓN DEL SERVICIO
陸|りく|RIKU|TIERRA / COSTA
着陸|ちゃくりく|CHAKURIKU|ATERRIZAJE / TOMA DE TIERRA
大陸|たいりく|TAIRIKU|UN CONTINENTE
陸上|りくじょう|RIKUJOU|EN TIERRA / SOBRE LA TIERRA
損|そん|SON|PÉRDIDA / DESVENTAJA
損傷|そんしょう|SONSHOU|DAÑO / LESIÓN
損害|そんがい|SONGAI|DAÑO / LESIÓN / PÉRDIDA
損得|そんとく|SONTOKU|PÉRDIDA Y GANANCIA
気候|きこう|KIKOU|CLIMA
天候|てんこう|TENKOU|TIEMPO ATMOSFÉRICO
風船|ふうせん|FUUSEN|UN GLOBO
造船|ぞうせん|ZOUSEN|CONSTRUCCIÓN NAVAL
船|ふね|FUNE|UN BARCO / BUQUE
船便|ふなびん|FUNABIN|CORREO MARÍTIMO / VÍA SUPERFICIAL
丸|まる|MARU|UN CÍRCULO
～丸|まる|MARU|SUFIJO PARA NOMBRE DE BARCOS
丸い|まるい|MARUI|REDONDO / CIRCULAR / ESFÉRICO
混雑|こんざつ|KONZATSU|CONFUSIÓN / CONGESTIÓN
混じる|まじる|MAJIRU|MEZCLARSE / ESTAR MEZCLADO
かき混ぜる|かきまぜる|KAKIMAZERU|REVOLVER / AGITAR
混ざる|まざる|MAZARU|MEZCLARSE / ESTAR MEZCLADO
予想|よそう|YOSOU|ANTICIPACIÓN / PREVISIÓN
感想|かんそう|KANSOU|IMPRESIONES / PENSAMIENTOS
想像|そうぞう|SOUZOU|IMAGINACIÓN / CONJETURA
理想|りそう|RISOU|IDEAL
事故|じこ|JIKO|UN ACCIDENTE
故障|こしょう|KOSHOU|AVERÍA / FALLO
故郷|こきょう|KOKYOU|PUEBLO NATAL / LUGAR DE NACIMIENTO
混乱|こんらん|KONRAN|DESORDEN / CONFUSIÓN
乱暴（な）|らんぼう（な）|RANBOU|RUDE / VIOLENTO / TOSCO
乱れる|みだれる|MIDARERU|CAER EN EL DESORDEN / DESORGANIZARSE
運河|うんが|UNGA|UN CANAL / VÍA FLUVIAL
河川|かせん|KASEN|UN RÍO / LOS RÍOS (TÉRMINO FORMAL)
河|かわ|KAWA|UN RÍO / ARROYO
輸出|ゆしゅつ|YUSHUTSU|EXPORTACIÓN
輸入|ゆにゅう|YUNYUU|IMPORTACIÓN
輸血|ゆけつ|YUKETSU|UNA TRANSFUSIÓN DE SANGRE
輸送|ゆそう|YUSOU|TRANSPORTE / TRANSPORTACIÓN


// --- Frases del repertorio del Jefe (Se elegirán 2 al azar cada 1000 puntos) ---
//BOSS_FRAS|frase japonesa|Frase en Romaji|Traducción al español
BOSS_FRAS|消費税は商品に均等に課税される。|SHOUHIZEIHASHOUHINNIKINTOUNIKAZEISARERU|EL IMPUESTO AL CONSUMO SE APLICA POR IGUAL A LOS PRODUCTOS.
BOSS_FRAS|「広告が事実と異なり、納得がいかない場合はこちらにご連絡を。」|KOUKOKUGAJIJITSUTOKOTANARINATTOKUGAIKANAIBAAIWHAKOCHIRANIGORENRAKUWO|«SI EL ANUNCIO DIFIERE DE LOS HECHOS Y NO ESTÁ SATISFECHO, PÓNGASE EN CONTACTO CON NOSOTROS AQUÍ».
BOSS_FRAS|「〇〇ランドの入場者数がすでに百万人を超えました。」|RANDONONYUUJOUSHASUUGASUDENIHYAKUMANNINWOKOEMASHITA|«EL NÚMERO DE ASISTENTES A XX LAND YA HA SUPERADO EL MILLÓN DE PERSONAS».
BOSS_FRAS|世界で最も物価の高い都市はどこでしょう。|SEKAIDEMOTTOMOBUKKANOTAKAITOSHIHADOKODESHOU|¿CUÁL SERÁ LA CIUDAD CON EL COSTO DE VIDA MÁS ALTO DEL MUNDO?
BOSS_FRAS|子供を対象としたテレビ番組を制作する。|KODOMOWOTAISHOUTOSHITATEREBIBANGUMIWOSEISAKUSURU|PRODUCIR UN PROGRAMA DE TELEVISIÓN DIRIGIDO A LOS NIÑOS.
BOSS_FRAS|コレステロールの数値が上がっているので注意してください。|KORESUTEROURUNOSUUCHIGAAGATTEIRUNODECHUUISHITEKUDASAI|POR FAVOR, TENGA CUIDADO PORQUE SUS NIVELES DE COLESTEROL ESTÁN SUBIENDO.
BOSS_FRAS|雨靴は無いが、ぬれてもいい靴ならある。|AMAGUTSUHANAIGANURETEMOIIKUTSUNARAARU|NO TENGO BOTAS DE AGUA, PERO SÍ ZAPATOS QUE NO IMPORTA QUE SE MOJEN.
BOSS_FRAS|この番組は〇〇食品の提供でお送りしました。|KONOBANGUMIHASHOKUHINNOTEIKYOUDEOOKURISHIMASHITA|ESTE PROGRAMA FUE PRESENTADO POR CORTESÍA DE ALIMENTOS XX.
BOSS_FRAS|草花や野菜、果物などを箱に詰めて出荷する。|KUSABANAYAYASAIKUDAMONONADOWOHAKONITSUMETESHUKKASURU|EMPAQUETAR FLORES, VERDURAS, FRUTAS, ETC., EN CAJAS Y ENVIARLAS AL MERCADO.
BOSS_FRAS|その作業は単純だが、ミスをすると危険だ。|SONOSAGYOUHATANJUNDAGAMISUWOSURUTOKIKENDA|ESE TRABAJO ES SIMPLE, PERO ES PELIGROSO SI SE COMETE UN ERROR.
BOSS_FRAS|商品を使ったり作ったりして見せて売ることを実演販売という。|SHOUHINWOTSUKATTARITSUKUTTARISHITEMISETEURUKOTOWOJITSUENHANBAITOIU|VENDER UN PRODUCTO MOSTRANDO CÓMO SE USA O CÓMO SE HACE SE LLAMA VENTA CON DEMOSTRACIÓN EN VIVO.
BOSS_FRAS|年に２回、住民による地域の除草作業が行われる。|NENNINIKAIJUUMINNIYORUCHIIKINOJOSOUSAGYOUGAOKONAWARERU|DOS VECES AL AÑO, LOS RESIDENTES LLEVAN A CABO LABORES DE DESHIERBE EN LA REGIÓN.
BOSS_FRAS|事故処理中の道路に、まだ車の破片が散らばっている。|JIKOSHORICHUUNODOURONIMADAKURUMANOHAHENGACHIRABATTEIRU|EN LA CARRETERA DONDE SE ESTÁ ATENDIENDO EL ACCIDENTE, TODAVÍA HAY FRAGMENTOS DE COCHE ESPARCIDOS.
BOSS_FRAS|贈り物の包装は指示カウンターで承ります。|OKURIMONONOHOUSOUHASHIJIKAUNTAADEUKETAMAWARIMASU|NOS ENCARGAMOS DEL ENVOLTORIO DE REGALOS EN EL MOSTRADOR DE SERVICIO.
BOSS_FRAS|省エネというのはエネルギーを節約することです。|SHOUENETOIUNOHAENERUGIIWOSETSUYAKUSURUKOTODESU|AHORRO DE ENERGÍA SIGNIFICA ECONOMIZAR ENERGÍA.
BOSS_FRAS|あのお相撲さんは現役を引退して解説者になるそうだ。|ANOOSUMOUSANHAGENEKIWOINTAISHITEKAISETSUSHANINARUSOUDA|DICEN QUE AQUEL LUCHADOR DE SUMO SE RETIRARÁ DEL SERVICIO ACTIVO PARA CONVERTIRSE EN COMENTARISTA.
BOSS_FRAS|週末は富士山の近くの温泉宿に泊まる予定です。|SHUUMATSUHAFUJISANNOCHIKAKUNOONSENYADONITOMARUYOTEIDESU|ESTE FIN DE SEMANA TENGO PLANEADO HOSPEDARME EN UNA POSADA DE AGUAS TERMALES CERCA DEL MONTE FUJI.
BOSS_FRAS|冬季オリンピック選手の帰国を空港でお出迎える。|TOUKIORINPIKKUSENSHUNOKIKOKUWOKUUKOUDEODEMUKAERU|RECIBIR EN EL AEROPUERTO A LOS ATLETAS DE LOS JUEGOS OLÍMPICOS DE INVIERNO QUE REGRESAN A CASA.
BOSS_FRAS|この町は自然に囲まれた緑豊かなところです。|KONOMACHIHASHIZENNIKAKOMARETAMIDORIYUTAKANATOKORODESU|ESTE PUEBLO ES UN LUGAR RODEADO DE NATURALEZA Y MUY RICO EN VEGETACIÓN.
BOSS_FRAS|明日から１泊２日の旅行に行きます。|ASHITAKARAIPPAKUFUTSUKANORYOKOUNIIKIMASU|A PARTIR DE MAÑANA IRÉ A UN VIAJE DE DOS DÍAS Y UNA NOCHE.
BOSS_FRAS|様々な角度からアプローチして問題を解決する。|SAMAZAMANAKAKUDOKARAAPROUCHISHITEMONDAIWOKAIKETSUSURU|ABORDAR EL PROBLEMA DESDE VARIOS ÁNGULOS PARA RESOLVERLO.
BOSS_FRAS|居間と食堂を合わせて１２畳です。|IMATOSHOKUDOUWOAWASETEJUUNIJOUDESU|LA SALA DE ESTAR Y EL COMEDOR JUNTOS MIDEN DOCE TATAMIS.
BOSS_FRAS|私は大学で建築の勉強をしています。|WATASHIHADAIGAKUDEKENCHIKUNOBENKYOUWOSHITEIMASU|ESTOY ESTUDIANDO ARQUITECTURA EN LA UNIVERSIDAD.
BOSS_FRAS|お金が必要になったので、定期預金を解約する。|OKANEGAHITSUYOUNINATTANODETEIKIYOKINWOKAIYAKUSURU|COMO NECESITABA DINERO, CANCELÉ MI DEPÓSITO A PLAZO FIJO.
BOSS_FRAS|この坂を上ると美しいお寺がありますよ。|KONOSAKAWONOBORUTOUTSUKUSHIIOTERAGAARIMASUYO|SI SUBES ESTA CUESTA, ENCONTRARÁS UN TEMPLO HERMOSO.
BOSS_FRAS|市役所は警察署の向かいにあります。|SHIYAKUSHOHAKEISATSUSHONOMUKAINIARIMASU|EL AYUNTAMIENTO ESTÁ ENFRENTE DE LA COMISARÍA DE POLICÍA.
BOSS_FRAS|日本に科学技術を学ぶために来ました。|NIHONNIKAGAKUGIJUTSUWOMANABUTAMENIKIMASHITA|VINE A JAPÓN PARA ESTUDIAR CIENCIA Y TECNOLOGÍA.
BOSS_FRAS|湖の岸に白鳥がたくさんいるのが見える。|MIZUUMINOKISHINIHAKUCHOUGATAKUSANIRUNOGAMIERU|SE PUEDE VER QUE HAY MUCHOS CISNES EN LA ORILLA DEL LAGO.
BOSS_FRAS|日本列島を北から南まで旅行してみたい。|NIHONRETTOUWOKITAKARAMINAMIMADERYOKOUSHITEMITAI|ME GUSTARÍA VIAJAR POR EL ARCHIPIÉLAGO JAPONÉS DESDE EL NORTE HASTA EL SUR.
BOSS_FRAS|この公園の中に、お城や植物園があります。|KONOKOUENONAKANIOSHIROYASHOKUBUTSUENGAARIMASU|DENTRO DE ESTE PARQUE HAY UN CASTILLO Y UN JARDÍN BOTÁNICO.
BOSS_FRAS|海岸には波で打ち寄せられたごみが落ちていた。|KAIGANNIHANAMIDEUCHIYOSERARETAGOMIGAAOCHITEITA|EN LA COSTA HABÍA BASURA QUE HABÍA SIDO ARRASTRADA POR LAS OLAS.
BOSS_FRAS|このツアーの観光コースにパリのエッフェル塔も入っています。|KONOTUAANOKANKOUKOUSUNIPARINOEFFERUTOUMOHAITTEIMASU|EL CONTEXTO TURÍSTICO DE ESTE VIAJE TAMBIÉN INCLUYE LA TORRE EIFFEL DE PARÍS.
BOSS_FRAS|この建物は国宝に指定されています。|KONOTATEMONOHAKOKUHOUNISHITEISARETEIMASU|ESTE EDIFICIO ESTÁ DECLARADO TESORO NACIONAL.
BOSS_FRAS|渋谷駅の犬の銅像の前で待ち合わせしましょう。|SHIBUYAEKINOINUNODOUZOUNOMAEDEMACHIAWASESHIMASHOU|QUEDEMOS EN LA ESTACIÓN DE SHIBUYA, FRENTE A LA ESTATUA DE BRONCE DEL PERRO.
BOSS_FRAS|あの国には３人の王子がいます。|ANOKUNINIHAASANNINNOOUJIGAIMASU|EN AQUEL PAÍS HAY TRES PRÍNCIPES.
BOSS_FRAS|有名な絵画の複製を部屋にかざる。|YUUMEINAKAIGANOFUKUSEIWOHEYANIKAZARU|DECORAR LA HABITACIÓN CON UNA RÉPLICA DE UNA PINTURA FAMOSA.
BOSS_FRAS|これに関する説明は複雑なため、ここでは省略します。|KORENIKANSURUSETSUMEIHAFUKUZATSUNATAMEKOKODEHASHOURYAKUSHIMASU|COMO LA EXPLICACIÓN SOBRE ESTO ES COMPLEJA, SE OMITIRÁ AQUÍ.
BOSS_FRAS|出版社の刊行物の案内を見て、注文する。|SHUPPANSHANOKANKOUBUTSUNOANNAIWOMITECHUUMONSURU|REVISAR EL CATÁLOGO DE PUBLICACIONES DE LA EDITORIAL Y HACER UN PEDIDO.
BOSS_FRAS|昨日、デパートでテレビによく出ている芸能人を見かけた。|KINOUDEPAATODETEREBINIYOKUDETEIRUGEINOUJINWOMIKAKETA|AYER EN LOS ALMACENES VI A UNA CELEBRIDAD QUE APARECE A MENUDO EN LA TELEVISIÓN.
BOSS_FRAS|バラを花束にすると一層甘い香りがする。|BARAWOHANATABANISURUTOISSOUAMAIKAORIGASURU|CUANDO SE HACE UN RAMO CON LAS ROSAS, SU FRAGANCIA DULCE ES AÚN MÁS INTENSA.
BOSS_FRAS|肌が弱い人は、綿のシャツを着るとよいでしょう。|HADAGAYOWAIHITOHAMENNOSHATSUWOKIRUTOYOIDESHOU|LAS PERSONAS CON PIEL SENSIBLE HARÍAN BIEN EN USAR CAMISAS DE ALGODÓN.
BOSS_FRAS|当店のスパゲティは一皿が２人前の量です。|TOUTENNOSUPAGETIIHAHITOSARAGANININMAENORYOUDESU|LOS ESPAGUETIS DE NUESTRO LOCAL TIENEN UNA CANTIDAD POR PLATO EQUIVALENTE A DOS RACIONES.
BOSS_FRAS|今は田中ですが、旧姓は林です。|IMAHATANAKADESUGAKYUUSEIHAHAYASHIDESU|AHORA SOY TANAKA, PERO MI APELLIDO DE SOLTERA ES HAYASHI.
BOSS_FRAS|「みそ汁、味が薄いから、今度からもう少し濃くして。」|MISOSHIRUAJIGAUSUIKARAKONDOKARAMOUSUKOSHIKOKUSHITE|«LA SOPA DE MISO TIENE UN SABOR MUY LIGERO, ASÍ QUE LA PRÓXIMA VEZ HAZLA UN POCO MÁS CONCENTRADA».
BOSS_FRAS|「一粒でお口の中がスッキリ、さわやか！〇〇キャンディー」|HITOTSUBUDEOKUCHINONAKAGASUKKIRISAWAYAKAKYANDII|«¡UN SOLO GRANO Y TU BOCA QUEDARÁ LIMPIA Y FRESCA! CARAMELOS XX»
BOSS_FRAS|「教育制度の改革に積極的に取り組もう！」|KYOUIKUSEIDONOKAIKAKUNISEKKYOKUTEKINITORIKUMOU|«¡TRABAJEMOS DE MANERA ACTIVA EN LA REFORMA DEL SISTEMA EDUCATIVO!»
BOSS_FRAS|フランス革命は1978年に起きた。|FURANSUKAKUMEIHA1978NENNIOKITA|LA REVOLUCIÓN FRANCESA OCURRIÓ EN EL AÑO 1978.
`.trim();