export const KATAKANA_RAW = `
キロ|KIRO|KILOGRAMO/KILÓMETRO
クラス|KURASU|CLASE
グラム|GURAMU|GRAMO
スポーツ|SUPOOTSU|DEPORTE
ニュース|NYUUSU|NOTICIAS
パーティー|PAATII|FIESTA
ページ|PEEJI|PÁGINA
メートル|MEETORU|METRO
エレベーター|EREBEETAA|ASCENSOR
デパート|DEPAATO|GRANDES ALMACENES
トイレ|TOIRE|BAÑO, SERVICIO
プール|PUURU|PISCINA
ホテル|HOTERU|HOTEL
レストラン|RESUTORAN|RESTAURANTE
コップ|KOPPU|VASO
ストーブ|SUTOOBU|ESTUFA
テーブル|TEEBURU|MESA
スプーン|SUPUUN|CUCHARA
ナイフ|NAIFU|CUCHILLO
フォーク|FOOKU|TENEDOR
バター|BATAA|MANTEQUILLA
シャツ|SHATSU|CAMISETA
ワイシャツ|WAISHATSU|CAMISA
セーター|SEETAA|SUÉTER
コート|KOOTO|ABRIGO
ネクタイ|NEKUTAI|CORBATA
ハンカチ|HANKACHI|PAÑUELO
ポケット|POKETTO|BOLSILLO
ズボン|ZUBON|PANTALÓN
スカート|SUKAATO|FALDA
スリッパ|SURIPPA|SANDALIAS
タクシー|TAKUSHII|TAXI
バス|BASU|AUTOBÚS
ラジオ|RAJIO|RADIO
レコード|REKOODO|DISCO
カメラ|KAMERA|CÁMARA
ギター|GITARAA|GUITARRA
テープ|TEEPU|CINTA
テープレコーダー|TEEPUREKOODAA|GRABADORA
テスト|TESUTO|EXAMEN
テレビ|TEREBI|TELEVISIÓN
ドア|DOA|PUERTA
フィルム|FIRUMU|PELÍCULA
ベッド|BEDDO|CAMA

BOSS_FRAS|デパートでシャツをかいました|DEPAATODESHATSUWOKAIMASHITA|Compré una camisa en los grandes almacenes
BOSS_FRAS|テーブルにコップがあります|TEEBURUNIKOPPUGAARIMASU|Hay un vaso en la mesa
BOSS_FRAS|クラスでテストをします|KURASUDETESUTOWOSHIMASU|Hago el examen en clase
BOSS_FRAS|ホテルのエレベーターはきれいです|HOTERUNOEREBEETAAHAKIREIDESU|El ascensor del hotel es bonito
BOSS_FRAS|レストランでスポーツのニュースをみました|RESUTORANDESUPOOTSUNONYUUSUOMIMASHITA|Vi las noticias de deportes en el restaurante
BOSS_FRAS|タクシーでプールへいきます|TAKUSHIDEPURUUEIKIMASU|Voy a la piscina en taxi
BOSS_FRAS|ワイシャツにネクタイをつけます|WAISHATSUNINEKUTAIWOTSUKEMASU|Me pongo la corbata en la camisa
BOSS_FRAS|ポケットにハンカチがあります|POKETTUNIHANKACHIGAARIMASU|Hay un pañuelo en el bolsillo
BOSS_FRAS|ベッドでラジオをききます|BEDDUDERAJIOWOKIKIMASU|Escucho la radio en la cama
BOSS_FRAS|ギターでページをめくります|GITAADEPEEJIWOMEKURIMASU|Paso la página con la guitarra
`.trim(); // El .trim() quita líneas vacías automáticamente